// Code generated by go-swagger; DO NOT EDIT.

package certificates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/TomerHeber/avatax-v2-go/models"
)

// LinkCustomersToCertificateReader is a Reader for the LinkCustomersToCertificate structure.
type LinkCustomersToCertificateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LinkCustomersToCertificateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLinkCustomersToCertificateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewLinkCustomersToCertificateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewLinkCustomersToCertificateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewLinkCustomersToCertificateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLinkCustomersToCertificateOK creates a LinkCustomersToCertificateOK with default headers values
func NewLinkCustomersToCertificateOK() *LinkCustomersToCertificateOK {
	return &LinkCustomersToCertificateOK{}
}

/* LinkCustomersToCertificateOK describes a response with status code 200, with default header values.

Success
*/
type LinkCustomersToCertificateOK struct {
	Payload *models.CustomerModelFetchResult
}

func (o *LinkCustomersToCertificateOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/companies/{companyId}/certificates/{id}/customers/link][%d] linkCustomersToCertificateOK  %+v", 200, o.Payload)
}
func (o *LinkCustomersToCertificateOK) GetPayload() *models.CustomerModelFetchResult {
	return o.Payload
}

func (o *LinkCustomersToCertificateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CustomerModelFetchResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLinkCustomersToCertificateBadRequest creates a LinkCustomersToCertificateBadRequest with default headers values
func NewLinkCustomersToCertificateBadRequest() *LinkCustomersToCertificateBadRequest {
	return &LinkCustomersToCertificateBadRequest{}
}

/* LinkCustomersToCertificateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type LinkCustomersToCertificateBadRequest struct {
}

func (o *LinkCustomersToCertificateBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/companies/{companyId}/certificates/{id}/customers/link][%d] linkCustomersToCertificateBadRequest ", 400)
}

func (o *LinkCustomersToCertificateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewLinkCustomersToCertificateUnauthorized creates a LinkCustomersToCertificateUnauthorized with default headers values
func NewLinkCustomersToCertificateUnauthorized() *LinkCustomersToCertificateUnauthorized {
	return &LinkCustomersToCertificateUnauthorized{}
}

/* LinkCustomersToCertificateUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type LinkCustomersToCertificateUnauthorized struct {
}

func (o *LinkCustomersToCertificateUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v2/companies/{companyId}/certificates/{id}/customers/link][%d] linkCustomersToCertificateUnauthorized ", 401)
}

func (o *LinkCustomersToCertificateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewLinkCustomersToCertificateNotFound creates a LinkCustomersToCertificateNotFound with default headers values
func NewLinkCustomersToCertificateNotFound() *LinkCustomersToCertificateNotFound {
	return &LinkCustomersToCertificateNotFound{}
}

/* LinkCustomersToCertificateNotFound describes a response with status code 404, with default header values.

Not Found
*/
type LinkCustomersToCertificateNotFound struct {
}

func (o *LinkCustomersToCertificateNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v2/companies/{companyId}/certificates/{id}/customers/link][%d] linkCustomersToCertificateNotFound ", 404)
}

func (o *LinkCustomersToCertificateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
