// Code generated by go-swagger; DO NOT EDIT.

package items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/TomerHeber/avatax-v2-go/models"
)

// GetItemReader is a Reader for the GetItem structure.
type GetItemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetItemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetItemOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetItemBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetItemUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetItemNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetItemOK creates a GetItemOK with default headers values
func NewGetItemOK() *GetItemOK {
	return &GetItemOK{}
}

/* GetItemOK describes a response with status code 200, with default header values.

Success
*/
type GetItemOK struct {
	Payload *models.ItemModel
}

func (o *GetItemOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/companies/{companyId}/items/{id}][%d] getItemOK  %+v", 200, o.Payload)
}
func (o *GetItemOK) GetPayload() *models.ItemModel {
	return o.Payload
}

func (o *GetItemOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ItemModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetItemBadRequest creates a GetItemBadRequest with default headers values
func NewGetItemBadRequest() *GetItemBadRequest {
	return &GetItemBadRequest{}
}

/* GetItemBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetItemBadRequest struct {
}

func (o *GetItemBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/companies/{companyId}/items/{id}][%d] getItemBadRequest ", 400)
}

func (o *GetItemBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetItemUnauthorized creates a GetItemUnauthorized with default headers values
func NewGetItemUnauthorized() *GetItemUnauthorized {
	return &GetItemUnauthorized{}
}

/* GetItemUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetItemUnauthorized struct {
}

func (o *GetItemUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v2/companies/{companyId}/items/{id}][%d] getItemUnauthorized ", 401)
}

func (o *GetItemUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetItemNotFound creates a GetItemNotFound with default headers values
func NewGetItemNotFound() *GetItemNotFound {
	return &GetItemNotFound{}
}

/* GetItemNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetItemNotFound struct {
}

func (o *GetItemNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v2/companies/{companyId}/items/{id}][%d] getItemNotFound ", 404)
}

func (o *GetItemNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
