// Code generated by go-swagger; DO NOT EDIT.

package firm_client_linkages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new firm client linkages API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for firm client linkages API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	ApproveFirmClientLinkage(params *ApproveFirmClientLinkageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ApproveFirmClientLinkageOK, error)

	CreateAndLinkNewFirmClientAccount(params *CreateAndLinkNewFirmClientAccountParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateAndLinkNewFirmClientAccountCreated, error)

	CreateFirmClientLinkage(params *CreateFirmClientLinkageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateFirmClientLinkageCreated, error)

	DeleteFirmClientLinkage(params *DeleteFirmClientLinkageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteFirmClientLinkageOK, error)

	GetFirmClientLinkage(params *GetFirmClientLinkageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetFirmClientLinkageOK, error)

	ListFirmClientLinkage(params *ListFirmClientLinkageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListFirmClientLinkageOK, error)

	RejectFirmClientLinkage(params *RejectFirmClientLinkageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RejectFirmClientLinkageOK, error)

	ResetFirmClientLinkage(params *ResetFirmClientLinkageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ResetFirmClientLinkageOK, error)

	RevokeFirmClientLinkage(params *RevokeFirmClientLinkageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RevokeFirmClientLinkageOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  ApproveFirmClientLinkage approves linkage to a firm for a client account

  This API enables the account admin of a client account to approve linkage request by a firm.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, FirmAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.

*/
func (a *Client) ApproveFirmClientLinkage(params *ApproveFirmClientLinkageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ApproveFirmClientLinkageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewApproveFirmClientLinkageParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ApproveFirmClientLinkage",
		Method:             "POST",
		PathPattern:        "/api/v2/firmclientlinkages/{id}/approve",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ApproveFirmClientLinkageReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ApproveFirmClientLinkageOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ApproveFirmClientLinkage: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  CreateAndLinkNewFirmClientAccount requests a new firm client account and create an approved linkage to it

  This API is for use by Firms only.

Avalara allows firms to manage returns for clients without the clients needing to use AvaTax service.
Firms can create accounts of FirmClient for customers they are managing using this API.

Calling this API creates an account with the specified product subscriptions, but without a new user for account.
Account is then linked to the Firm so they can managed their returns.
You should call this API when a customer does not have an AvaTax account and is to be managed only by the firm.

The created account will be created in `Active` status but there will be no user or license key associated with account.

### Security Policies

* This API requires one of the following user roles: FirmAdmin, Registrar, SiteAdmin, SystemAdmin.

*/
func (a *Client) CreateAndLinkNewFirmClientAccount(params *CreateAndLinkNewFirmClientAccountParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateAndLinkNewFirmClientAccountCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateAndLinkNewFirmClientAccountParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateAndLinkNewFirmClientAccount",
		Method:             "POST",
		PathPattern:        "/api/v2/firmclientlinkages/createandlinkclient",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/*+json", "application/json", "application/json-patch+json", "text/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateAndLinkNewFirmClientAccountReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateAndLinkNewFirmClientAccountCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for CreateAndLinkNewFirmClientAccount: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  CreateFirmClientLinkage links a firm account with the client account

  This API enables the firm admins/firm users to request the linkage of a firm account and a client account.

### Security Policies

* This API requires one of the following user roles: FirmAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.

*/
func (a *Client) CreateFirmClientLinkage(params *CreateFirmClientLinkageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateFirmClientLinkageCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateFirmClientLinkageParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateFirmClientLinkage",
		Method:             "POST",
		PathPattern:        "/api/v2/firmclientlinkages",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/*+json", "application/json", "application/json-patch+json", "text/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateFirmClientLinkageReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateFirmClientLinkageCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for CreateFirmClientLinkage: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DeleteFirmClientLinkage deletes a linkage

  This API marks a linkage between a firm and client as deleted.

### Security Policies

* This API requires one of the following user roles: FirmAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.

*/
func (a *Client) DeleteFirmClientLinkage(params *DeleteFirmClientLinkageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteFirmClientLinkageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteFirmClientLinkageParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteFirmClientLinkage",
		Method:             "DELETE",
		PathPattern:        "/api/v2/firmclientlinkages/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteFirmClientLinkageReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteFirmClientLinkageOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteFirmClientLinkage: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetFirmClientLinkage gets linkage between a firm and client by id

  This API enables the firm admins/firm users to request the linkage of a firm account and a client account.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, AccountUser, CompanyAdmin, CompanyUser, Compliance Root User, ComplianceAdmin, ComplianceUser, CSPAdmin, CSPTester, FirmAdmin, FirmUser, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.

*/
func (a *Client) GetFirmClientLinkage(params *GetFirmClientLinkageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetFirmClientLinkageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetFirmClientLinkageParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetFirmClientLinkage",
		Method:             "GET",
		PathPattern:        "/api/v2/firmclientlinkages/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetFirmClientLinkageReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetFirmClientLinkageOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetFirmClientLinkage: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ListFirmClientLinkage lists client linkages for a firm or client

  This API enables the firm or account users to request the associated linkages to the account.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, AccountUser, CompanyAdmin, CompanyUser, Compliance Root User, ComplianceAdmin, ComplianceUser, CSPAdmin, CSPTester, FirmAdmin, FirmUser, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.

*/
func (a *Client) ListFirmClientLinkage(params *ListFirmClientLinkageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListFirmClientLinkageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListFirmClientLinkageParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListFirmClientLinkage",
		Method:             "GET",
		PathPattern:        "/api/v2/firmclientlinkages",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListFirmClientLinkageReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListFirmClientLinkageOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ListFirmClientLinkage: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  RejectFirmClientLinkage rejects linkage to a firm for a client account

  This API enables the account admin of a client account to reject linkage request by a firm.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, FirmAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.

*/
func (a *Client) RejectFirmClientLinkage(params *RejectFirmClientLinkageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RejectFirmClientLinkageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRejectFirmClientLinkageParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "RejectFirmClientLinkage",
		Method:             "POST",
		PathPattern:        "/api/v2/firmclientlinkages/{id}/reject",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &RejectFirmClientLinkageReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*RejectFirmClientLinkageOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for RejectFirmClientLinkage: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ResetFirmClientLinkage resets linkage status between a client and firm back to requested

  This API enables the firm admin of a client account to reset a previously created linkage request by a firm.

### Security Policies

* This API requires one of the following user roles: FirmAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.

*/
func (a *Client) ResetFirmClientLinkage(params *ResetFirmClientLinkageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ResetFirmClientLinkageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewResetFirmClientLinkageParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ResetFirmClientLinkage",
		Method:             "POST",
		PathPattern:        "/api/v2/firmclientlinkages/{id}/reset",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ResetFirmClientLinkageReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ResetFirmClientLinkageOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ResetFirmClientLinkage: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  RevokeFirmClientLinkage revokes previously approved linkage to a firm for a client account

  This API enables the account admin of a client account to revoke a previously approved linkage request by a firm.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, FirmAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.

*/
func (a *Client) RevokeFirmClientLinkage(params *RevokeFirmClientLinkageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RevokeFirmClientLinkageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRevokeFirmClientLinkageParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "RevokeFirmClientLinkage",
		Method:             "POST",
		PathPattern:        "/api/v2/firmclientlinkages/{id}/revoke",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &RevokeFirmClientLinkageReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*RevokeFirmClientLinkageOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for RevokeFirmClientLinkage: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
