// Code generated by go-swagger; DO NOT EDIT.

package firm_client_linkages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListFirmClientLinkageParams creates a new ListFirmClientLinkageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListFirmClientLinkageParams() *ListFirmClientLinkageParams {
	return &ListFirmClientLinkageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListFirmClientLinkageParamsWithTimeout creates a new ListFirmClientLinkageParams object
// with the ability to set a timeout on a request.
func NewListFirmClientLinkageParamsWithTimeout(timeout time.Duration) *ListFirmClientLinkageParams {
	return &ListFirmClientLinkageParams{
		timeout: timeout,
	}
}

// NewListFirmClientLinkageParamsWithContext creates a new ListFirmClientLinkageParams object
// with the ability to set a context for a request.
func NewListFirmClientLinkageParamsWithContext(ctx context.Context) *ListFirmClientLinkageParams {
	return &ListFirmClientLinkageParams{
		Context: ctx,
	}
}

// NewListFirmClientLinkageParamsWithHTTPClient creates a new ListFirmClientLinkageParams object
// with the ability to set a custom HTTPClient for a request.
func NewListFirmClientLinkageParamsWithHTTPClient(client *http.Client) *ListFirmClientLinkageParams {
	return &ListFirmClientLinkageParams{
		HTTPClient: client,
	}
}

/* ListFirmClientLinkageParams contains all the parameters to send to the API endpoint
   for the list firm client linkage operation.

   Typically these are written to a http.Request.
*/
type ListFirmClientLinkageParams struct {

	/* DollarFilter.

	   A filter statement to identify specific records to retrieve.  For more information on filtering, see [Filtering in REST](http://developer.avalara.com/avatax/filtering-in-rest/).<br />*Not filterable:* firmAccountName, clientAccountName
	*/
	DollarFilter *string

	/* XAvalaraClient.

	   Identifies the software you are using to call this API.  For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/) .

	   Default: "Swagger UI; 21.12.0; Custom; 1.0"
	*/
	XAvalaraClient *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list firm client linkage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListFirmClientLinkageParams) WithDefaults() *ListFirmClientLinkageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list firm client linkage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListFirmClientLinkageParams) SetDefaults() {
	var (
		xAvalaraClientDefault = string("Swagger UI; 21.12.0; Custom; 1.0")
	)

	val := ListFirmClientLinkageParams{
		XAvalaraClient: &xAvalaraClientDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the list firm client linkage params
func (o *ListFirmClientLinkageParams) WithTimeout(timeout time.Duration) *ListFirmClientLinkageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list firm client linkage params
func (o *ListFirmClientLinkageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list firm client linkage params
func (o *ListFirmClientLinkageParams) WithContext(ctx context.Context) *ListFirmClientLinkageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list firm client linkage params
func (o *ListFirmClientLinkageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list firm client linkage params
func (o *ListFirmClientLinkageParams) WithHTTPClient(client *http.Client) *ListFirmClientLinkageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list firm client linkage params
func (o *ListFirmClientLinkageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDollarFilter adds the dollarFilter to the list firm client linkage params
func (o *ListFirmClientLinkageParams) WithDollarFilter(dollarFilter *string) *ListFirmClientLinkageParams {
	o.SetDollarFilter(dollarFilter)
	return o
}

// SetDollarFilter adds the dollarFilter to the list firm client linkage params
func (o *ListFirmClientLinkageParams) SetDollarFilter(dollarFilter *string) {
	o.DollarFilter = dollarFilter
}

// WithXAvalaraClient adds the xAvalaraClient to the list firm client linkage params
func (o *ListFirmClientLinkageParams) WithXAvalaraClient(xAvalaraClient *string) *ListFirmClientLinkageParams {
	o.SetXAvalaraClient(xAvalaraClient)
	return o
}

// SetXAvalaraClient adds the xAvalaraClient to the list firm client linkage params
func (o *ListFirmClientLinkageParams) SetXAvalaraClient(xAvalaraClient *string) {
	o.XAvalaraClient = xAvalaraClient
}

// WriteToRequest writes these params to a swagger request
func (o *ListFirmClientLinkageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DollarFilter != nil {

		// query param $filter
		var qrDollarFilter string

		if o.DollarFilter != nil {
			qrDollarFilter = *o.DollarFilter
		}
		qDollarFilter := qrDollarFilter
		if qDollarFilter != "" {

			if err := r.SetQueryParam("$filter", qDollarFilter); err != nil {
				return err
			}
		}
	}

	if o.XAvalaraClient != nil {

		// header param X-Avalara-Client
		if err := r.SetHeaderParam("X-Avalara-Client", *o.XAvalaraClient); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
