// Code generated by go-swagger; DO NOT EDIT.

package firm_client_linkages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/TomerHeber/avatax-v2-go/models"
)

// ListFirmClientLinkageReader is a Reader for the ListFirmClientLinkage structure.
type ListFirmClientLinkageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListFirmClientLinkageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListFirmClientLinkageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListFirmClientLinkageBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListFirmClientLinkageUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListFirmClientLinkageOK creates a ListFirmClientLinkageOK with default headers values
func NewListFirmClientLinkageOK() *ListFirmClientLinkageOK {
	return &ListFirmClientLinkageOK{}
}

/* ListFirmClientLinkageOK describes a response with status code 200, with default header values.

Success
*/
type ListFirmClientLinkageOK struct {
	Payload *models.FirmClientLinkageOutputModelFetchResult
}

func (o *ListFirmClientLinkageOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/firmclientlinkages][%d] listFirmClientLinkageOK  %+v", 200, o.Payload)
}
func (o *ListFirmClientLinkageOK) GetPayload() *models.FirmClientLinkageOutputModelFetchResult {
	return o.Payload
}

func (o *ListFirmClientLinkageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FirmClientLinkageOutputModelFetchResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListFirmClientLinkageBadRequest creates a ListFirmClientLinkageBadRequest with default headers values
func NewListFirmClientLinkageBadRequest() *ListFirmClientLinkageBadRequest {
	return &ListFirmClientLinkageBadRequest{}
}

/* ListFirmClientLinkageBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ListFirmClientLinkageBadRequest struct {
}

func (o *ListFirmClientLinkageBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/firmclientlinkages][%d] listFirmClientLinkageBadRequest ", 400)
}

func (o *ListFirmClientLinkageBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListFirmClientLinkageUnauthorized creates a ListFirmClientLinkageUnauthorized with default headers values
func NewListFirmClientLinkageUnauthorized() *ListFirmClientLinkageUnauthorized {
	return &ListFirmClientLinkageUnauthorized{}
}

/* ListFirmClientLinkageUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ListFirmClientLinkageUnauthorized struct {
}

func (o *ListFirmClientLinkageUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v2/firmclientlinkages][%d] listFirmClientLinkageUnauthorized ", 401)
}

func (o *ListFirmClientLinkageUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
