// Code generated by go-swagger; DO NOT EDIT.

package contacts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/TomerHeber/avatax-v2-go/models"
)

// CreateContactsReader is a Reader for the CreateContacts structure.
type CreateContactsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateContactsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateContactsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateContactsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateContactsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateContactsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateContactsOK creates a CreateContactsOK with default headers values
func NewCreateContactsOK() *CreateContactsOK {
	return &CreateContactsOK{}
}

/* CreateContactsOK describes a response with status code 200, with default header values.

Success
*/
type CreateContactsOK struct {
	Payload []*models.ContactModel
}

func (o *CreateContactsOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/companies/{companyId}/contacts][%d] createContactsOK  %+v", 200, o.Payload)
}
func (o *CreateContactsOK) GetPayload() []*models.ContactModel {
	return o.Payload
}

func (o *CreateContactsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateContactsBadRequest creates a CreateContactsBadRequest with default headers values
func NewCreateContactsBadRequest() *CreateContactsBadRequest {
	return &CreateContactsBadRequest{}
}

/* CreateContactsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateContactsBadRequest struct {
}

func (o *CreateContactsBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/companies/{companyId}/contacts][%d] createContactsBadRequest ", 400)
}

func (o *CreateContactsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateContactsUnauthorized creates a CreateContactsUnauthorized with default headers values
func NewCreateContactsUnauthorized() *CreateContactsUnauthorized {
	return &CreateContactsUnauthorized{}
}

/* CreateContactsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateContactsUnauthorized struct {
}

func (o *CreateContactsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v2/companies/{companyId}/contacts][%d] createContactsUnauthorized ", 401)
}

func (o *CreateContactsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateContactsNotFound creates a CreateContactsNotFound with default headers values
func NewCreateContactsNotFound() *CreateContactsNotFound {
	return &CreateContactsNotFound{}
}

/* CreateContactsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CreateContactsNotFound struct {
}

func (o *CreateContactsNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v2/companies/{companyId}/contacts][%d] createContactsNotFound ", 404)
}

func (o *CreateContactsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
