// Code generated by go-swagger; DO NOT EDIT.

package data_sources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/TomerHeber/avatax-v2-go/models"
)

// UpdateDataSourceReader is a Reader for the UpdateDataSource structure.
type UpdateDataSourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateDataSourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateDataSourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateDataSourceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateDataSourceUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateDataSourceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateDataSourceOK creates a UpdateDataSourceOK with default headers values
func NewUpdateDataSourceOK() *UpdateDataSourceOK {
	return &UpdateDataSourceOK{}
}

/* UpdateDataSourceOK describes a response with status code 200, with default header values.

Success
*/
type UpdateDataSourceOK struct {
	Payload *models.DataSourceModel
}

func (o *UpdateDataSourceOK) Error() string {
	return fmt.Sprintf("[PUT /api/v2/companies/{companyId}/datasources/{id}][%d] updateDataSourceOK  %+v", 200, o.Payload)
}
func (o *UpdateDataSourceOK) GetPayload() *models.DataSourceModel {
	return o.Payload
}

func (o *UpdateDataSourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DataSourceModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateDataSourceBadRequest creates a UpdateDataSourceBadRequest with default headers values
func NewUpdateDataSourceBadRequest() *UpdateDataSourceBadRequest {
	return &UpdateDataSourceBadRequest{}
}

/* UpdateDataSourceBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UpdateDataSourceBadRequest struct {
}

func (o *UpdateDataSourceBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/v2/companies/{companyId}/datasources/{id}][%d] updateDataSourceBadRequest ", 400)
}

func (o *UpdateDataSourceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateDataSourceUnauthorized creates a UpdateDataSourceUnauthorized with default headers values
func NewUpdateDataSourceUnauthorized() *UpdateDataSourceUnauthorized {
	return &UpdateDataSourceUnauthorized{}
}

/* UpdateDataSourceUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type UpdateDataSourceUnauthorized struct {
}

func (o *UpdateDataSourceUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /api/v2/companies/{companyId}/datasources/{id}][%d] updateDataSourceUnauthorized ", 401)
}

func (o *UpdateDataSourceUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateDataSourceNotFound creates a UpdateDataSourceNotFound with default headers values
func NewUpdateDataSourceNotFound() *UpdateDataSourceNotFound {
	return &UpdateDataSourceNotFound{}
}

/* UpdateDataSourceNotFound describes a response with status code 404, with default header values.

Not Found
*/
type UpdateDataSourceNotFound struct {
}

func (o *UpdateDataSourceNotFound) Error() string {
	return fmt.Sprintf("[PUT /api/v2/companies/{companyId}/datasources/{id}][%d] updateDataSourceNotFound ", 404)
}

func (o *UpdateDataSourceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
