// Code generated by go-swagger; DO NOT EDIT.

package distance_thresholds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/TomerHeber/avatax-v2-go/models"
)

// NewCreateDistanceThresholdParams creates a new CreateDistanceThresholdParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateDistanceThresholdParams() *CreateDistanceThresholdParams {
	return &CreateDistanceThresholdParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDistanceThresholdParamsWithTimeout creates a new CreateDistanceThresholdParams object
// with the ability to set a timeout on a request.
func NewCreateDistanceThresholdParamsWithTimeout(timeout time.Duration) *CreateDistanceThresholdParams {
	return &CreateDistanceThresholdParams{
		timeout: timeout,
	}
}

// NewCreateDistanceThresholdParamsWithContext creates a new CreateDistanceThresholdParams object
// with the ability to set a context for a request.
func NewCreateDistanceThresholdParamsWithContext(ctx context.Context) *CreateDistanceThresholdParams {
	return &CreateDistanceThresholdParams{
		Context: ctx,
	}
}

// NewCreateDistanceThresholdParamsWithHTTPClient creates a new CreateDistanceThresholdParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateDistanceThresholdParamsWithHTTPClient(client *http.Client) *CreateDistanceThresholdParams {
	return &CreateDistanceThresholdParams{
		HTTPClient: client,
	}
}

/* CreateDistanceThresholdParams contains all the parameters to send to the API endpoint
   for the create distance threshold operation.

   Typically these are written to a http.Request.
*/
type CreateDistanceThresholdParams struct {

	/* XAvalaraClient.

	   Identifies the software you are using to call this API.  For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/) .

	   Default: "Swagger UI; 21.12.0; Custom; 1.0"
	*/
	XAvalaraClient *string

	/* Body.

	   The DistanceThreshold object or objects you wish to create.
	*/
	Body []*models.CompanyDistanceThresholdModel

	/* CompanyID.

	   The unique ID number of the company that owns this DistanceThreshold

	   Format: int32
	*/
	CompanyID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create distance threshold params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDistanceThresholdParams) WithDefaults() *CreateDistanceThresholdParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create distance threshold params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDistanceThresholdParams) SetDefaults() {
	var (
		xAvalaraClientDefault = string("Swagger UI; 21.12.0; Custom; 1.0")
	)

	val := CreateDistanceThresholdParams{
		XAvalaraClient: &xAvalaraClientDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the create distance threshold params
func (o *CreateDistanceThresholdParams) WithTimeout(timeout time.Duration) *CreateDistanceThresholdParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create distance threshold params
func (o *CreateDistanceThresholdParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create distance threshold params
func (o *CreateDistanceThresholdParams) WithContext(ctx context.Context) *CreateDistanceThresholdParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create distance threshold params
func (o *CreateDistanceThresholdParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create distance threshold params
func (o *CreateDistanceThresholdParams) WithHTTPClient(client *http.Client) *CreateDistanceThresholdParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create distance threshold params
func (o *CreateDistanceThresholdParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAvalaraClient adds the xAvalaraClient to the create distance threshold params
func (o *CreateDistanceThresholdParams) WithXAvalaraClient(xAvalaraClient *string) *CreateDistanceThresholdParams {
	o.SetXAvalaraClient(xAvalaraClient)
	return o
}

// SetXAvalaraClient adds the xAvalaraClient to the create distance threshold params
func (o *CreateDistanceThresholdParams) SetXAvalaraClient(xAvalaraClient *string) {
	o.XAvalaraClient = xAvalaraClient
}

// WithBody adds the body to the create distance threshold params
func (o *CreateDistanceThresholdParams) WithBody(body []*models.CompanyDistanceThresholdModel) *CreateDistanceThresholdParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create distance threshold params
func (o *CreateDistanceThresholdParams) SetBody(body []*models.CompanyDistanceThresholdModel) {
	o.Body = body
}

// WithCompanyID adds the companyID to the create distance threshold params
func (o *CreateDistanceThresholdParams) WithCompanyID(companyID int32) *CreateDistanceThresholdParams {
	o.SetCompanyID(companyID)
	return o
}

// SetCompanyID adds the companyId to the create distance threshold params
func (o *CreateDistanceThresholdParams) SetCompanyID(companyID int32) {
	o.CompanyID = companyID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDistanceThresholdParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XAvalaraClient != nil {

		// header param X-Avalara-Client
		if err := r.SetHeaderParam("X-Avalara-Client", *o.XAvalaraClient); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param companyId
	if err := r.SetPathParam("companyId", swag.FormatInt32(o.CompanyID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
