// Code generated by go-swagger; DO NOT EDIT.

package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListSubscriptionsByAccountParams creates a new ListSubscriptionsByAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListSubscriptionsByAccountParams() *ListSubscriptionsByAccountParams {
	return &ListSubscriptionsByAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListSubscriptionsByAccountParamsWithTimeout creates a new ListSubscriptionsByAccountParams object
// with the ability to set a timeout on a request.
func NewListSubscriptionsByAccountParamsWithTimeout(timeout time.Duration) *ListSubscriptionsByAccountParams {
	return &ListSubscriptionsByAccountParams{
		timeout: timeout,
	}
}

// NewListSubscriptionsByAccountParamsWithContext creates a new ListSubscriptionsByAccountParams object
// with the ability to set a context for a request.
func NewListSubscriptionsByAccountParamsWithContext(ctx context.Context) *ListSubscriptionsByAccountParams {
	return &ListSubscriptionsByAccountParams{
		Context: ctx,
	}
}

// NewListSubscriptionsByAccountParamsWithHTTPClient creates a new ListSubscriptionsByAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewListSubscriptionsByAccountParamsWithHTTPClient(client *http.Client) *ListSubscriptionsByAccountParams {
	return &ListSubscriptionsByAccountParams{
		HTTPClient: client,
	}
}

/* ListSubscriptionsByAccountParams contains all the parameters to send to the API endpoint
   for the list subscriptions by account operation.

   Typically these are written to a http.Request.
*/
type ListSubscriptionsByAccountParams struct {

	/* DollarFilter.

	   A filter statement to identify specific records to retrieve.  For more information on filtering, see [Filtering in REST](http://developer.avalara.com/avatax/filtering-in-rest/).<br />*Not filterable:* subscriptionDescription
	*/
	DollarFilter *string

	/* DollarOrderBy.

	   A comma separated list of sort statements in the format `(fieldname) [ASC|DESC]`, for example `id ASC`.
	*/
	DollarOrderBy *string

	/* DollarSkip.

	   If nonzero, skip this number of results before returning data.  Used with `$top` to provide pagination for large datasets.

	   Format: int32
	*/
	DollarSkip *int32

	/* DollarTop.

	   If nonzero, return no more than this number of results.  Used with `$skip` to provide pagination for large datasets.  Unless otherwise specified, the maximum number of records that can be returned from an API call is 1,000 records.

	   Format: int32
	*/
	DollarTop *int32

	/* XAvalaraClient.

	   Identifies the software you are using to call this API.  For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/) .

	   Default: "Swagger UI; 21.12.0; Custom; 1.0"
	*/
	XAvalaraClient *string

	/* AccountID.

	   The ID of the account that owns these subscriptions

	   Format: int32
	*/
	AccountID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list subscriptions by account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListSubscriptionsByAccountParams) WithDefaults() *ListSubscriptionsByAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list subscriptions by account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListSubscriptionsByAccountParams) SetDefaults() {
	var (
		xAvalaraClientDefault = string("Swagger UI; 21.12.0; Custom; 1.0")
	)

	val := ListSubscriptionsByAccountParams{
		XAvalaraClient: &xAvalaraClientDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the list subscriptions by account params
func (o *ListSubscriptionsByAccountParams) WithTimeout(timeout time.Duration) *ListSubscriptionsByAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list subscriptions by account params
func (o *ListSubscriptionsByAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list subscriptions by account params
func (o *ListSubscriptionsByAccountParams) WithContext(ctx context.Context) *ListSubscriptionsByAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list subscriptions by account params
func (o *ListSubscriptionsByAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list subscriptions by account params
func (o *ListSubscriptionsByAccountParams) WithHTTPClient(client *http.Client) *ListSubscriptionsByAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list subscriptions by account params
func (o *ListSubscriptionsByAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDollarFilter adds the dollarFilter to the list subscriptions by account params
func (o *ListSubscriptionsByAccountParams) WithDollarFilter(dollarFilter *string) *ListSubscriptionsByAccountParams {
	o.SetDollarFilter(dollarFilter)
	return o
}

// SetDollarFilter adds the dollarFilter to the list subscriptions by account params
func (o *ListSubscriptionsByAccountParams) SetDollarFilter(dollarFilter *string) {
	o.DollarFilter = dollarFilter
}

// WithDollarOrderBy adds the dollarOrderBy to the list subscriptions by account params
func (o *ListSubscriptionsByAccountParams) WithDollarOrderBy(dollarOrderBy *string) *ListSubscriptionsByAccountParams {
	o.SetDollarOrderBy(dollarOrderBy)
	return o
}

// SetDollarOrderBy adds the dollarOrderBy to the list subscriptions by account params
func (o *ListSubscriptionsByAccountParams) SetDollarOrderBy(dollarOrderBy *string) {
	o.DollarOrderBy = dollarOrderBy
}

// WithDollarSkip adds the dollarSkip to the list subscriptions by account params
func (o *ListSubscriptionsByAccountParams) WithDollarSkip(dollarSkip *int32) *ListSubscriptionsByAccountParams {
	o.SetDollarSkip(dollarSkip)
	return o
}

// SetDollarSkip adds the dollarSkip to the list subscriptions by account params
func (o *ListSubscriptionsByAccountParams) SetDollarSkip(dollarSkip *int32) {
	o.DollarSkip = dollarSkip
}

// WithDollarTop adds the dollarTop to the list subscriptions by account params
func (o *ListSubscriptionsByAccountParams) WithDollarTop(dollarTop *int32) *ListSubscriptionsByAccountParams {
	o.SetDollarTop(dollarTop)
	return o
}

// SetDollarTop adds the dollarTop to the list subscriptions by account params
func (o *ListSubscriptionsByAccountParams) SetDollarTop(dollarTop *int32) {
	o.DollarTop = dollarTop
}

// WithXAvalaraClient adds the xAvalaraClient to the list subscriptions by account params
func (o *ListSubscriptionsByAccountParams) WithXAvalaraClient(xAvalaraClient *string) *ListSubscriptionsByAccountParams {
	o.SetXAvalaraClient(xAvalaraClient)
	return o
}

// SetXAvalaraClient adds the xAvalaraClient to the list subscriptions by account params
func (o *ListSubscriptionsByAccountParams) SetXAvalaraClient(xAvalaraClient *string) {
	o.XAvalaraClient = xAvalaraClient
}

// WithAccountID adds the accountID to the list subscriptions by account params
func (o *ListSubscriptionsByAccountParams) WithAccountID(accountID int32) *ListSubscriptionsByAccountParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the list subscriptions by account params
func (o *ListSubscriptionsByAccountParams) SetAccountID(accountID int32) {
	o.AccountID = accountID
}

// WriteToRequest writes these params to a swagger request
func (o *ListSubscriptionsByAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DollarFilter != nil {

		// query param $filter
		var qrDollarFilter string

		if o.DollarFilter != nil {
			qrDollarFilter = *o.DollarFilter
		}
		qDollarFilter := qrDollarFilter
		if qDollarFilter != "" {

			if err := r.SetQueryParam("$filter", qDollarFilter); err != nil {
				return err
			}
		}
	}

	if o.DollarOrderBy != nil {

		// query param $orderBy
		var qrDollarOrderBy string

		if o.DollarOrderBy != nil {
			qrDollarOrderBy = *o.DollarOrderBy
		}
		qDollarOrderBy := qrDollarOrderBy
		if qDollarOrderBy != "" {

			if err := r.SetQueryParam("$orderBy", qDollarOrderBy); err != nil {
				return err
			}
		}
	}

	if o.DollarSkip != nil {

		// query param $skip
		var qrDollarSkip int32

		if o.DollarSkip != nil {
			qrDollarSkip = *o.DollarSkip
		}
		qDollarSkip := swag.FormatInt32(qrDollarSkip)
		if qDollarSkip != "" {

			if err := r.SetQueryParam("$skip", qDollarSkip); err != nil {
				return err
			}
		}
	}

	if o.DollarTop != nil {

		// query param $top
		var qrDollarTop int32

		if o.DollarTop != nil {
			qrDollarTop = *o.DollarTop
		}
		qDollarTop := swag.FormatInt32(qrDollarTop)
		if qDollarTop != "" {

			if err := r.SetQueryParam("$top", qDollarTop); err != nil {
				return err
			}
		}
	}

	if o.XAvalaraClient != nil {

		// header param X-Avalara-Client
		if err := r.SetHeaderParam("X-Avalara-Client", *o.XAvalaraClient); err != nil {
			return err
		}
	}

	// path param accountId
	if err := r.SetPathParam("accountId", swag.FormatInt32(o.AccountID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
