// Code generated by go-swagger; DO NOT EDIT.

package locations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/TomerHeber/avatax-v2-go/models"
)

// QueryLocationsReader is a Reader for the QueryLocations structure.
type QueryLocationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QueryLocationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewQueryLocationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewQueryLocationsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewQueryLocationsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewQueryLocationsOK creates a QueryLocationsOK with default headers values
func NewQueryLocationsOK() *QueryLocationsOK {
	return &QueryLocationsOK{}
}

/* QueryLocationsOK describes a response with status code 200, with default header values.

Success
*/
type QueryLocationsOK struct {
	Payload *models.LocationModelFetchResult
}

func (o *QueryLocationsOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/locations][%d] queryLocationsOK  %+v", 200, o.Payload)
}
func (o *QueryLocationsOK) GetPayload() *models.LocationModelFetchResult {
	return o.Payload
}

func (o *QueryLocationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LocationModelFetchResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryLocationsBadRequest creates a QueryLocationsBadRequest with default headers values
func NewQueryLocationsBadRequest() *QueryLocationsBadRequest {
	return &QueryLocationsBadRequest{}
}

/* QueryLocationsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type QueryLocationsBadRequest struct {
}

func (o *QueryLocationsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/locations][%d] queryLocationsBadRequest ", 400)
}

func (o *QueryLocationsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewQueryLocationsUnauthorized creates a QueryLocationsUnauthorized with default headers values
func NewQueryLocationsUnauthorized() *QueryLocationsUnauthorized {
	return &QueryLocationsUnauthorized{}
}

/* QueryLocationsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type QueryLocationsUnauthorized struct {
}

func (o *QueryLocationsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v2/locations][%d] queryLocationsUnauthorized ", 401)
}

func (o *QueryLocationsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
