// Code generated by go-swagger; DO NOT EDIT.

package user_defined_fields

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListUserDefinedFieldsByCompanyIDParams creates a new ListUserDefinedFieldsByCompanyIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListUserDefinedFieldsByCompanyIDParams() *ListUserDefinedFieldsByCompanyIDParams {
	return &ListUserDefinedFieldsByCompanyIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListUserDefinedFieldsByCompanyIDParamsWithTimeout creates a new ListUserDefinedFieldsByCompanyIDParams object
// with the ability to set a timeout on a request.
func NewListUserDefinedFieldsByCompanyIDParamsWithTimeout(timeout time.Duration) *ListUserDefinedFieldsByCompanyIDParams {
	return &ListUserDefinedFieldsByCompanyIDParams{
		timeout: timeout,
	}
}

// NewListUserDefinedFieldsByCompanyIDParamsWithContext creates a new ListUserDefinedFieldsByCompanyIDParams object
// with the ability to set a context for a request.
func NewListUserDefinedFieldsByCompanyIDParamsWithContext(ctx context.Context) *ListUserDefinedFieldsByCompanyIDParams {
	return &ListUserDefinedFieldsByCompanyIDParams{
		Context: ctx,
	}
}

// NewListUserDefinedFieldsByCompanyIDParamsWithHTTPClient creates a new ListUserDefinedFieldsByCompanyIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewListUserDefinedFieldsByCompanyIDParamsWithHTTPClient(client *http.Client) *ListUserDefinedFieldsByCompanyIDParams {
	return &ListUserDefinedFieldsByCompanyIDParams{
		HTTPClient: client,
	}
}

/* ListUserDefinedFieldsByCompanyIDParams contains all the parameters to send to the API endpoint
   for the list user defined fields by company Id operation.

   Typically these are written to a http.Request.
*/
type ListUserDefinedFieldsByCompanyIDParams struct {

	/* XAvalaraClient.

	   Identifies the software you are using to call this API.  For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/) .

	   Default: "Swagger UI; 21.12.0; Custom; 1.0"
	*/
	XAvalaraClient *string

	/* AllowDefaults.

	   If true this will add defaulted UDFs to the list that are not named yet

	   Default: true
	*/
	AllowDefaults *bool

	// CompanyID.
	//
	// Format: int32
	CompanyID int32

	/* UdfType.

	   Document or Line level UDF

	   Default: "Document"
	*/
	UdfType *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list user defined fields by company Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListUserDefinedFieldsByCompanyIDParams) WithDefaults() *ListUserDefinedFieldsByCompanyIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list user defined fields by company Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListUserDefinedFieldsByCompanyIDParams) SetDefaults() {
	var (
		xAvalaraClientDefault = string("Swagger UI; 21.12.0; Custom; 1.0")

		allowDefaultsDefault = bool(true)

		udfTypeDefault = string("Document")
	)

	val := ListUserDefinedFieldsByCompanyIDParams{
		XAvalaraClient: &xAvalaraClientDefault,
		AllowDefaults:  &allowDefaultsDefault,
		UdfType:        &udfTypeDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the list user defined fields by company Id params
func (o *ListUserDefinedFieldsByCompanyIDParams) WithTimeout(timeout time.Duration) *ListUserDefinedFieldsByCompanyIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list user defined fields by company Id params
func (o *ListUserDefinedFieldsByCompanyIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list user defined fields by company Id params
func (o *ListUserDefinedFieldsByCompanyIDParams) WithContext(ctx context.Context) *ListUserDefinedFieldsByCompanyIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list user defined fields by company Id params
func (o *ListUserDefinedFieldsByCompanyIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list user defined fields by company Id params
func (o *ListUserDefinedFieldsByCompanyIDParams) WithHTTPClient(client *http.Client) *ListUserDefinedFieldsByCompanyIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list user defined fields by company Id params
func (o *ListUserDefinedFieldsByCompanyIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAvalaraClient adds the xAvalaraClient to the list user defined fields by company Id params
func (o *ListUserDefinedFieldsByCompanyIDParams) WithXAvalaraClient(xAvalaraClient *string) *ListUserDefinedFieldsByCompanyIDParams {
	o.SetXAvalaraClient(xAvalaraClient)
	return o
}

// SetXAvalaraClient adds the xAvalaraClient to the list user defined fields by company Id params
func (o *ListUserDefinedFieldsByCompanyIDParams) SetXAvalaraClient(xAvalaraClient *string) {
	o.XAvalaraClient = xAvalaraClient
}

// WithAllowDefaults adds the allowDefaults to the list user defined fields by company Id params
func (o *ListUserDefinedFieldsByCompanyIDParams) WithAllowDefaults(allowDefaults *bool) *ListUserDefinedFieldsByCompanyIDParams {
	o.SetAllowDefaults(allowDefaults)
	return o
}

// SetAllowDefaults adds the allowDefaults to the list user defined fields by company Id params
func (o *ListUserDefinedFieldsByCompanyIDParams) SetAllowDefaults(allowDefaults *bool) {
	o.AllowDefaults = allowDefaults
}

// WithCompanyID adds the companyID to the list user defined fields by company Id params
func (o *ListUserDefinedFieldsByCompanyIDParams) WithCompanyID(companyID int32) *ListUserDefinedFieldsByCompanyIDParams {
	o.SetCompanyID(companyID)
	return o
}

// SetCompanyID adds the companyId to the list user defined fields by company Id params
func (o *ListUserDefinedFieldsByCompanyIDParams) SetCompanyID(companyID int32) {
	o.CompanyID = companyID
}

// WithUdfType adds the udfType to the list user defined fields by company Id params
func (o *ListUserDefinedFieldsByCompanyIDParams) WithUdfType(udfType *string) *ListUserDefinedFieldsByCompanyIDParams {
	o.SetUdfType(udfType)
	return o
}

// SetUdfType adds the udfType to the list user defined fields by company Id params
func (o *ListUserDefinedFieldsByCompanyIDParams) SetUdfType(udfType *string) {
	o.UdfType = udfType
}

// WriteToRequest writes these params to a swagger request
func (o *ListUserDefinedFieldsByCompanyIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XAvalaraClient != nil {

		// header param X-Avalara-Client
		if err := r.SetHeaderParam("X-Avalara-Client", *o.XAvalaraClient); err != nil {
			return err
		}
	}

	if o.AllowDefaults != nil {

		// query param allowDefaults
		var qrAllowDefaults bool

		if o.AllowDefaults != nil {
			qrAllowDefaults = *o.AllowDefaults
		}
		qAllowDefaults := swag.FormatBool(qrAllowDefaults)
		if qAllowDefaults != "" {

			if err := r.SetQueryParam("allowDefaults", qAllowDefaults); err != nil {
				return err
			}
		}
	}

	// path param companyId
	if err := r.SetPathParam("companyId", swag.FormatInt32(o.CompanyID)); err != nil {
		return err
	}

	if o.UdfType != nil {

		// query param udfType
		var qrUdfType string

		if o.UdfType != nil {
			qrUdfType = *o.UdfType
		}
		qUdfType := qrUdfType
		if qUdfType != "" {

			if err := r.SetQueryParam("udfType", qUdfType); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
