// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/TomerHeber/avatax-v2-go/models"
)

// SettleTransactionReader is a Reader for the SettleTransaction structure.
type SettleTransactionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SettleTransactionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSettleTransactionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSettleTransactionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSettleTransactionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSettleTransactionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSettleTransactionOK creates a SettleTransactionOK with default headers values
func NewSettleTransactionOK() *SettleTransactionOK {
	return &SettleTransactionOK{}
}

/* SettleTransactionOK describes a response with status code 200, with default header values.

Success
*/
type SettleTransactionOK struct {
	Payload *models.TransactionModel
}

func (o *SettleTransactionOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/companies/{companyCode}/transactions/{transactionCode}/settle][%d] settleTransactionOK  %+v", 200, o.Payload)
}
func (o *SettleTransactionOK) GetPayload() *models.TransactionModel {
	return o.Payload
}

func (o *SettleTransactionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TransactionModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSettleTransactionBadRequest creates a SettleTransactionBadRequest with default headers values
func NewSettleTransactionBadRequest() *SettleTransactionBadRequest {
	return &SettleTransactionBadRequest{}
}

/* SettleTransactionBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type SettleTransactionBadRequest struct {
}

func (o *SettleTransactionBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/companies/{companyCode}/transactions/{transactionCode}/settle][%d] settleTransactionBadRequest ", 400)
}

func (o *SettleTransactionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSettleTransactionUnauthorized creates a SettleTransactionUnauthorized with default headers values
func NewSettleTransactionUnauthorized() *SettleTransactionUnauthorized {
	return &SettleTransactionUnauthorized{}
}

/* SettleTransactionUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type SettleTransactionUnauthorized struct {
}

func (o *SettleTransactionUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v2/companies/{companyCode}/transactions/{transactionCode}/settle][%d] settleTransactionUnauthorized ", 401)
}

func (o *SettleTransactionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSettleTransactionNotFound creates a SettleTransactionNotFound with default headers values
func NewSettleTransactionNotFound() *SettleTransactionNotFound {
	return &SettleTransactionNotFound{}
}

/* SettleTransactionNotFound describes a response with status code 404, with default header values.

Not Found
*/
type SettleTransactionNotFound struct {
}

func (o *SettleTransactionNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v2/companies/{companyCode}/transactions/{transactionCode}/settle][%d] settleTransactionNotFound ", 404)
}

func (o *SettleTransactionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
