// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/TomerHeber/avatax-v2-go/models"
)

// NewVoidTransactionParams creates a new VoidTransactionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVoidTransactionParams() *VoidTransactionParams {
	return &VoidTransactionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVoidTransactionParamsWithTimeout creates a new VoidTransactionParams object
// with the ability to set a timeout on a request.
func NewVoidTransactionParamsWithTimeout(timeout time.Duration) *VoidTransactionParams {
	return &VoidTransactionParams{
		timeout: timeout,
	}
}

// NewVoidTransactionParamsWithContext creates a new VoidTransactionParams object
// with the ability to set a context for a request.
func NewVoidTransactionParamsWithContext(ctx context.Context) *VoidTransactionParams {
	return &VoidTransactionParams{
		Context: ctx,
	}
}

// NewVoidTransactionParamsWithHTTPClient creates a new VoidTransactionParams object
// with the ability to set a custom HTTPClient for a request.
func NewVoidTransactionParamsWithHTTPClient(client *http.Client) *VoidTransactionParams {
	return &VoidTransactionParams{
		HTTPClient: client,
	}
}

/* VoidTransactionParams contains all the parameters to send to the API endpoint
   for the void transaction operation.

   Typically these are written to a http.Request.
*/
type VoidTransactionParams struct {

	/* DollarInclude.

	   Specifies objects to include in this fetch call
	*/
	DollarInclude *string

	/* XAvalaraClient.

	   Identifies the software you are using to call this API.  For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/) .

	   Default: "Swagger UI; 21.12.0; Custom; 1.0"
	*/
	XAvalaraClient *string

	/* Body.

	   The void request you wish to execute. To void a transaction the code must be set to 'DocVoided'
	*/
	Body *models.VoidTransactionModel

	/* CompanyCode.

	   The company code of the company that recorded this transaction
	*/
	CompanyCode string

	/* DocumentType.

	   (Optional): The document type of the transaction to void. If not provided, the default is SalesInvoice.
	*/
	DocumentType *string

	/* TransactionCode.

	   The transaction code to void
	*/
	TransactionCode string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the void transaction params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VoidTransactionParams) WithDefaults() *VoidTransactionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the void transaction params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VoidTransactionParams) SetDefaults() {
	var (
		xAvalaraClientDefault = string("Swagger UI; 21.12.0; Custom; 1.0")
	)

	val := VoidTransactionParams{
		XAvalaraClient: &xAvalaraClientDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the void transaction params
func (o *VoidTransactionParams) WithTimeout(timeout time.Duration) *VoidTransactionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the void transaction params
func (o *VoidTransactionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the void transaction params
func (o *VoidTransactionParams) WithContext(ctx context.Context) *VoidTransactionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the void transaction params
func (o *VoidTransactionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the void transaction params
func (o *VoidTransactionParams) WithHTTPClient(client *http.Client) *VoidTransactionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the void transaction params
func (o *VoidTransactionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDollarInclude adds the dollarInclude to the void transaction params
func (o *VoidTransactionParams) WithDollarInclude(dollarInclude *string) *VoidTransactionParams {
	o.SetDollarInclude(dollarInclude)
	return o
}

// SetDollarInclude adds the dollarInclude to the void transaction params
func (o *VoidTransactionParams) SetDollarInclude(dollarInclude *string) {
	o.DollarInclude = dollarInclude
}

// WithXAvalaraClient adds the xAvalaraClient to the void transaction params
func (o *VoidTransactionParams) WithXAvalaraClient(xAvalaraClient *string) *VoidTransactionParams {
	o.SetXAvalaraClient(xAvalaraClient)
	return o
}

// SetXAvalaraClient adds the xAvalaraClient to the void transaction params
func (o *VoidTransactionParams) SetXAvalaraClient(xAvalaraClient *string) {
	o.XAvalaraClient = xAvalaraClient
}

// WithBody adds the body to the void transaction params
func (o *VoidTransactionParams) WithBody(body *models.VoidTransactionModel) *VoidTransactionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the void transaction params
func (o *VoidTransactionParams) SetBody(body *models.VoidTransactionModel) {
	o.Body = body
}

// WithCompanyCode adds the companyCode to the void transaction params
func (o *VoidTransactionParams) WithCompanyCode(companyCode string) *VoidTransactionParams {
	o.SetCompanyCode(companyCode)
	return o
}

// SetCompanyCode adds the companyCode to the void transaction params
func (o *VoidTransactionParams) SetCompanyCode(companyCode string) {
	o.CompanyCode = companyCode
}

// WithDocumentType adds the documentType to the void transaction params
func (o *VoidTransactionParams) WithDocumentType(documentType *string) *VoidTransactionParams {
	o.SetDocumentType(documentType)
	return o
}

// SetDocumentType adds the documentType to the void transaction params
func (o *VoidTransactionParams) SetDocumentType(documentType *string) {
	o.DocumentType = documentType
}

// WithTransactionCode adds the transactionCode to the void transaction params
func (o *VoidTransactionParams) WithTransactionCode(transactionCode string) *VoidTransactionParams {
	o.SetTransactionCode(transactionCode)
	return o
}

// SetTransactionCode adds the transactionCode to the void transaction params
func (o *VoidTransactionParams) SetTransactionCode(transactionCode string) {
	o.TransactionCode = transactionCode
}

// WriteToRequest writes these params to a swagger request
func (o *VoidTransactionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DollarInclude != nil {

		// query param $include
		var qrDollarInclude string

		if o.DollarInclude != nil {
			qrDollarInclude = *o.DollarInclude
		}
		qDollarInclude := qrDollarInclude
		if qDollarInclude != "" {

			if err := r.SetQueryParam("$include", qDollarInclude); err != nil {
				return err
			}
		}
	}

	if o.XAvalaraClient != nil {

		// header param X-Avalara-Client
		if err := r.SetHeaderParam("X-Avalara-Client", *o.XAvalaraClient); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param companyCode
	if err := r.SetPathParam("companyCode", o.CompanyCode); err != nil {
		return err
	}

	if o.DocumentType != nil {

		// query param documentType
		var qrDocumentType string

		if o.DocumentType != nil {
			qrDocumentType = *o.DocumentType
		}
		qDocumentType := qrDocumentType
		if qDocumentType != "" {

			if err := r.SetQueryParam("documentType", qDocumentType); err != nil {
				return err
			}
		}
	}

	// path param transactionCode
	if err := r.SetPathParam("transactionCode", o.TransactionCode); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
