// Code generated by go-swagger; DO NOT EDIT.

package registrar

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/TomerHeber/avatax-v2-go/models"
)

// DeleteAccountReader is a Reader for the DeleteAccount structure.
type DeleteAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteAccountBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteAccountUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAccountNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAccountOK creates a DeleteAccountOK with default headers values
func NewDeleteAccountOK() *DeleteAccountOK {
	return &DeleteAccountOK{}
}

/* DeleteAccountOK describes a response with status code 200, with default header values.

Success
*/
type DeleteAccountOK struct {
	Payload []*models.ErrorDetail
}

func (o *DeleteAccountOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/accounts/{id}][%d] deleteAccountOK  %+v", 200, o.Payload)
}
func (o *DeleteAccountOK) GetPayload() []*models.ErrorDetail {
	return o.Payload
}

func (o *DeleteAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAccountBadRequest creates a DeleteAccountBadRequest with default headers values
func NewDeleteAccountBadRequest() *DeleteAccountBadRequest {
	return &DeleteAccountBadRequest{}
}

/* DeleteAccountBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteAccountBadRequest struct {
}

func (o *DeleteAccountBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/accounts/{id}][%d] deleteAccountBadRequest ", 400)
}

func (o *DeleteAccountBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAccountUnauthorized creates a DeleteAccountUnauthorized with default headers values
func NewDeleteAccountUnauthorized() *DeleteAccountUnauthorized {
	return &DeleteAccountUnauthorized{}
}

/* DeleteAccountUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteAccountUnauthorized struct {
}

func (o *DeleteAccountUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/accounts/{id}][%d] deleteAccountUnauthorized ", 401)
}

func (o *DeleteAccountUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAccountNotFound creates a DeleteAccountNotFound with default headers values
func NewDeleteAccountNotFound() *DeleteAccountNotFound {
	return &DeleteAccountNotFound{}
}

/* DeleteAccountNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteAccountNotFound struct {
}

func (o *DeleteAccountNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/accounts/{id}][%d] deleteAccountNotFound ", 404)
}

func (o *DeleteAccountNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
