// Code generated by go-swagger; DO NOT EDIT.

package registrar

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/TomerHeber/avatax-v2-go/models"
)

// ListAccountsByTssWriteModeReader is a Reader for the ListAccountsByTssWriteMode structure.
type ListAccountsByTssWriteModeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAccountsByTssWriteModeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListAccountsByTssWriteModeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListAccountsByTssWriteModeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListAccountsByTssWriteModeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListAccountsByTssWriteModeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListAccountsByTssWriteModeOK creates a ListAccountsByTssWriteModeOK with default headers values
func NewListAccountsByTssWriteModeOK() *ListAccountsByTssWriteModeOK {
	return &ListAccountsByTssWriteModeOK{}
}

/* ListAccountsByTssWriteModeOK describes a response with status code 200, with default header values.

Success
*/
type ListAccountsByTssWriteModeOK struct {
	Payload *models.AccountMigrationStatusModel
}

func (o *ListAccountsByTssWriteModeOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/accounts/ListAccountsByTssWriteMode/{writeMode}][%d] listAccountsByTssWriteModeOK  %+v", 200, o.Payload)
}
func (o *ListAccountsByTssWriteModeOK) GetPayload() *models.AccountMigrationStatusModel {
	return o.Payload
}

func (o *ListAccountsByTssWriteModeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountMigrationStatusModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAccountsByTssWriteModeBadRequest creates a ListAccountsByTssWriteModeBadRequest with default headers values
func NewListAccountsByTssWriteModeBadRequest() *ListAccountsByTssWriteModeBadRequest {
	return &ListAccountsByTssWriteModeBadRequest{}
}

/* ListAccountsByTssWriteModeBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ListAccountsByTssWriteModeBadRequest struct {
}

func (o *ListAccountsByTssWriteModeBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/accounts/ListAccountsByTssWriteMode/{writeMode}][%d] listAccountsByTssWriteModeBadRequest ", 400)
}

func (o *ListAccountsByTssWriteModeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListAccountsByTssWriteModeUnauthorized creates a ListAccountsByTssWriteModeUnauthorized with default headers values
func NewListAccountsByTssWriteModeUnauthorized() *ListAccountsByTssWriteModeUnauthorized {
	return &ListAccountsByTssWriteModeUnauthorized{}
}

/* ListAccountsByTssWriteModeUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ListAccountsByTssWriteModeUnauthorized struct {
}

func (o *ListAccountsByTssWriteModeUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v2/accounts/ListAccountsByTssWriteMode/{writeMode}][%d] listAccountsByTssWriteModeUnauthorized ", 401)
}

func (o *ListAccountsByTssWriteModeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListAccountsByTssWriteModeNotFound creates a ListAccountsByTssWriteModeNotFound with default headers values
func NewListAccountsByTssWriteModeNotFound() *ListAccountsByTssWriteModeNotFound {
	return &ListAccountsByTssWriteModeNotFound{}
}

/* ListAccountsByTssWriteModeNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ListAccountsByTssWriteModeNotFound struct {
}

func (o *ListAccountsByTssWriteModeNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v2/accounts/ListAccountsByTssWriteMode/{writeMode}][%d] listAccountsByTssWriteModeNotFound ", 404)
}

func (o *ListAccountsByTssWriteModeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
