// Code generated by go-swagger; DO NOT EDIT.

package definitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListTaxTypesByNexusAndCountryParams creates a new ListTaxTypesByNexusAndCountryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListTaxTypesByNexusAndCountryParams() *ListTaxTypesByNexusAndCountryParams {
	return &ListTaxTypesByNexusAndCountryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListTaxTypesByNexusAndCountryParamsWithTimeout creates a new ListTaxTypesByNexusAndCountryParams object
// with the ability to set a timeout on a request.
func NewListTaxTypesByNexusAndCountryParamsWithTimeout(timeout time.Duration) *ListTaxTypesByNexusAndCountryParams {
	return &ListTaxTypesByNexusAndCountryParams{
		timeout: timeout,
	}
}

// NewListTaxTypesByNexusAndCountryParamsWithContext creates a new ListTaxTypesByNexusAndCountryParams object
// with the ability to set a context for a request.
func NewListTaxTypesByNexusAndCountryParamsWithContext(ctx context.Context) *ListTaxTypesByNexusAndCountryParams {
	return &ListTaxTypesByNexusAndCountryParams{
		Context: ctx,
	}
}

// NewListTaxTypesByNexusAndCountryParamsWithHTTPClient creates a new ListTaxTypesByNexusAndCountryParams object
// with the ability to set a custom HTTPClient for a request.
func NewListTaxTypesByNexusAndCountryParamsWithHTTPClient(client *http.Client) *ListTaxTypesByNexusAndCountryParams {
	return &ListTaxTypesByNexusAndCountryParams{
		HTTPClient: client,
	}
}

/* ListTaxTypesByNexusAndCountryParams contains all the parameters to send to the API endpoint
   for the list tax types by nexus and country operation.

   Typically these are written to a http.Request.
*/
type ListTaxTypesByNexusAndCountryParams struct {

	/* DollarOrderBy.

	   A comma separated list of sort statements in the format `(fieldname) [ASC|DESC]`, for example `id ASC`.
	*/
	DollarOrderBy *string

	/* DollarSkip.

	   If nonzero, skip this number of results before returning data.  Used with `$top` to provide pagination for large datasets.

	   Format: int32
	*/
	DollarSkip *int32

	/* DollarTop.

	   If nonzero, return no more than this number of results.  Used with `$skip` to provide pagination for large datasets.  Unless otherwise specified, the maximum number of records that can be returned from an API call is 1,000 records.

	   Format: int32
	*/
	DollarTop *int32

	/* XAvalaraClient.

	   Identifies the software you are using to call this API.  For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/) .

	   Default: "Swagger UI; 21.12.0; Custom; 1.0"
	*/
	XAvalaraClient *string

	/* CompanyID.

	   Your companyId to retrieve the applicable taxtypes

	   Format: int32
	*/
	CompanyID int32

	/* Country.

	   The country for which you want to retrieve the unitofbasis information
	*/
	Country string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list tax types by nexus and country params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListTaxTypesByNexusAndCountryParams) WithDefaults() *ListTaxTypesByNexusAndCountryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list tax types by nexus and country params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListTaxTypesByNexusAndCountryParams) SetDefaults() {
	var (
		xAvalaraClientDefault = string("Swagger UI; 21.12.0; Custom; 1.0")
	)

	val := ListTaxTypesByNexusAndCountryParams{
		XAvalaraClient: &xAvalaraClientDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the list tax types by nexus and country params
func (o *ListTaxTypesByNexusAndCountryParams) WithTimeout(timeout time.Duration) *ListTaxTypesByNexusAndCountryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list tax types by nexus and country params
func (o *ListTaxTypesByNexusAndCountryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list tax types by nexus and country params
func (o *ListTaxTypesByNexusAndCountryParams) WithContext(ctx context.Context) *ListTaxTypesByNexusAndCountryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list tax types by nexus and country params
func (o *ListTaxTypesByNexusAndCountryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list tax types by nexus and country params
func (o *ListTaxTypesByNexusAndCountryParams) WithHTTPClient(client *http.Client) *ListTaxTypesByNexusAndCountryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list tax types by nexus and country params
func (o *ListTaxTypesByNexusAndCountryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDollarOrderBy adds the dollarOrderBy to the list tax types by nexus and country params
func (o *ListTaxTypesByNexusAndCountryParams) WithDollarOrderBy(dollarOrderBy *string) *ListTaxTypesByNexusAndCountryParams {
	o.SetDollarOrderBy(dollarOrderBy)
	return o
}

// SetDollarOrderBy adds the dollarOrderBy to the list tax types by nexus and country params
func (o *ListTaxTypesByNexusAndCountryParams) SetDollarOrderBy(dollarOrderBy *string) {
	o.DollarOrderBy = dollarOrderBy
}

// WithDollarSkip adds the dollarSkip to the list tax types by nexus and country params
func (o *ListTaxTypesByNexusAndCountryParams) WithDollarSkip(dollarSkip *int32) *ListTaxTypesByNexusAndCountryParams {
	o.SetDollarSkip(dollarSkip)
	return o
}

// SetDollarSkip adds the dollarSkip to the list tax types by nexus and country params
func (o *ListTaxTypesByNexusAndCountryParams) SetDollarSkip(dollarSkip *int32) {
	o.DollarSkip = dollarSkip
}

// WithDollarTop adds the dollarTop to the list tax types by nexus and country params
func (o *ListTaxTypesByNexusAndCountryParams) WithDollarTop(dollarTop *int32) *ListTaxTypesByNexusAndCountryParams {
	o.SetDollarTop(dollarTop)
	return o
}

// SetDollarTop adds the dollarTop to the list tax types by nexus and country params
func (o *ListTaxTypesByNexusAndCountryParams) SetDollarTop(dollarTop *int32) {
	o.DollarTop = dollarTop
}

// WithXAvalaraClient adds the xAvalaraClient to the list tax types by nexus and country params
func (o *ListTaxTypesByNexusAndCountryParams) WithXAvalaraClient(xAvalaraClient *string) *ListTaxTypesByNexusAndCountryParams {
	o.SetXAvalaraClient(xAvalaraClient)
	return o
}

// SetXAvalaraClient adds the xAvalaraClient to the list tax types by nexus and country params
func (o *ListTaxTypesByNexusAndCountryParams) SetXAvalaraClient(xAvalaraClient *string) {
	o.XAvalaraClient = xAvalaraClient
}

// WithCompanyID adds the companyID to the list tax types by nexus and country params
func (o *ListTaxTypesByNexusAndCountryParams) WithCompanyID(companyID int32) *ListTaxTypesByNexusAndCountryParams {
	o.SetCompanyID(companyID)
	return o
}

// SetCompanyID adds the companyId to the list tax types by nexus and country params
func (o *ListTaxTypesByNexusAndCountryParams) SetCompanyID(companyID int32) {
	o.CompanyID = companyID
}

// WithCountry adds the country to the list tax types by nexus and country params
func (o *ListTaxTypesByNexusAndCountryParams) WithCountry(country string) *ListTaxTypesByNexusAndCountryParams {
	o.SetCountry(country)
	return o
}

// SetCountry adds the country to the list tax types by nexus and country params
func (o *ListTaxTypesByNexusAndCountryParams) SetCountry(country string) {
	o.Country = country
}

// WriteToRequest writes these params to a swagger request
func (o *ListTaxTypesByNexusAndCountryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DollarOrderBy != nil {

		// query param $orderBy
		var qrDollarOrderBy string

		if o.DollarOrderBy != nil {
			qrDollarOrderBy = *o.DollarOrderBy
		}
		qDollarOrderBy := qrDollarOrderBy
		if qDollarOrderBy != "" {

			if err := r.SetQueryParam("$orderBy", qDollarOrderBy); err != nil {
				return err
			}
		}
	}

	if o.DollarSkip != nil {

		// query param $skip
		var qrDollarSkip int32

		if o.DollarSkip != nil {
			qrDollarSkip = *o.DollarSkip
		}
		qDollarSkip := swag.FormatInt32(qrDollarSkip)
		if qDollarSkip != "" {

			if err := r.SetQueryParam("$skip", qDollarSkip); err != nil {
				return err
			}
		}
	}

	if o.DollarTop != nil {

		// query param $top
		var qrDollarTop int32

		if o.DollarTop != nil {
			qrDollarTop = *o.DollarTop
		}
		qDollarTop := swag.FormatInt32(qrDollarTop)
		if qDollarTop != "" {

			if err := r.SetQueryParam("$top", qDollarTop); err != nil {
				return err
			}
		}
	}

	if o.XAvalaraClient != nil {

		// header param X-Avalara-Client
		if err := r.SetHeaderParam("X-Avalara-Client", *o.XAvalaraClient); err != nil {
			return err
		}
	}

	// query param companyId
	qrCompanyID := o.CompanyID
	qCompanyID := swag.FormatInt32(qrCompanyID)
	if qCompanyID != "" {

		if err := r.SetQueryParam("companyId", qCompanyID); err != nil {
			return err
		}
	}

	// path param country
	if err := r.SetPathParam("country", o.Country); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
