// Code generated by go-swagger; DO NOT EDIT.

package definitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/TomerHeber/avatax-v2-go/models"
)

// ListCrossBorderSectionsReader is a Reader for the ListCrossBorderSections structure.
type ListCrossBorderSectionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListCrossBorderSectionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListCrossBorderSectionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListCrossBorderSectionsOK creates a ListCrossBorderSectionsOK with default headers values
func NewListCrossBorderSectionsOK() *ListCrossBorderSectionsOK {
	return &ListCrossBorderSectionsOK{}
}

/* ListCrossBorderSectionsOK describes a response with status code 200, with default header values.

Success
*/
type ListCrossBorderSectionsOK struct {
	Payload *models.HsCodeModelFetchResult
}

func (o *ListCrossBorderSectionsOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/definitions/crossborder/sections][%d] listCrossBorderSectionsOK  %+v", 200, o.Payload)
}
func (o *ListCrossBorderSectionsOK) GetPayload() *models.HsCodeModelFetchResult {
	return o.Payload
}

func (o *ListCrossBorderSectionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HsCodeModelFetchResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
