// Code generated by go-swagger; DO NOT EDIT.

package filings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetFiledReturnsParams creates a new GetFiledReturnsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFiledReturnsParams() *GetFiledReturnsParams {
	return &GetFiledReturnsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFiledReturnsParamsWithTimeout creates a new GetFiledReturnsParams object
// with the ability to set a timeout on a request.
func NewGetFiledReturnsParamsWithTimeout(timeout time.Duration) *GetFiledReturnsParams {
	return &GetFiledReturnsParams{
		timeout: timeout,
	}
}

// NewGetFiledReturnsParamsWithContext creates a new GetFiledReturnsParams object
// with the ability to set a context for a request.
func NewGetFiledReturnsParamsWithContext(ctx context.Context) *GetFiledReturnsParams {
	return &GetFiledReturnsParams{
		Context: ctx,
	}
}

// NewGetFiledReturnsParamsWithHTTPClient creates a new GetFiledReturnsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFiledReturnsParamsWithHTTPClient(client *http.Client) *GetFiledReturnsParams {
	return &GetFiledReturnsParams{
		HTTPClient: client,
	}
}

/* GetFiledReturnsParams contains all the parameters to send to the API endpoint
   for the get filed returns operation.

   Typically these are written to a http.Request.
*/
type GetFiledReturnsParams struct {

	/* XAvalaraClient.

	   Identifies the software you are using to call this API.  For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/) .

	   Default: "Swagger UI; 21.12.0; Custom; 1.0"
	*/
	XAvalaraClient *string

	/* CompanyID.

	   The ID of the company that owns these batches

	   Format: int32
	*/
	CompanyID int32

	/* Country.

	   The country of the return(s) you are trying to retrieve
	*/
	Country *string

	/* EndPeriodMonth.

	   The month of the period you are trying to retrieve

	   Format: int32
	*/
	EndPeriodMonth *int32

	/* EndPeriodYear.

	   The year of the period you are trying to retrieve

	   Format: int32
	*/
	EndPeriodYear *int32

	/* FilingCalendarID.

	   The filing calendar id of the return you are trying to retrieve

	   Format: int64
	*/
	FilingCalendarID *int64

	/* Frequency.

	   The frequency of the return you are trying to retrieve
	*/
	Frequency *string

	/* Region.

	   The region of the return(s) you are trying to retrieve
	*/
	Region *string

	/* Status.

	   The status of the return(s) you are trying to retrieve
	*/
	Status *string

	/* TaxformCode.

	   The unique tax form code of the form.
	*/
	TaxformCode *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get filed returns params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFiledReturnsParams) WithDefaults() *GetFiledReturnsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get filed returns params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFiledReturnsParams) SetDefaults() {
	var (
		xAvalaraClientDefault = string("Swagger UI; 21.12.0; Custom; 1.0")
	)

	val := GetFiledReturnsParams{
		XAvalaraClient: &xAvalaraClientDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get filed returns params
func (o *GetFiledReturnsParams) WithTimeout(timeout time.Duration) *GetFiledReturnsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get filed returns params
func (o *GetFiledReturnsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get filed returns params
func (o *GetFiledReturnsParams) WithContext(ctx context.Context) *GetFiledReturnsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get filed returns params
func (o *GetFiledReturnsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get filed returns params
func (o *GetFiledReturnsParams) WithHTTPClient(client *http.Client) *GetFiledReturnsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get filed returns params
func (o *GetFiledReturnsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAvalaraClient adds the xAvalaraClient to the get filed returns params
func (o *GetFiledReturnsParams) WithXAvalaraClient(xAvalaraClient *string) *GetFiledReturnsParams {
	o.SetXAvalaraClient(xAvalaraClient)
	return o
}

// SetXAvalaraClient adds the xAvalaraClient to the get filed returns params
func (o *GetFiledReturnsParams) SetXAvalaraClient(xAvalaraClient *string) {
	o.XAvalaraClient = xAvalaraClient
}

// WithCompanyID adds the companyID to the get filed returns params
func (o *GetFiledReturnsParams) WithCompanyID(companyID int32) *GetFiledReturnsParams {
	o.SetCompanyID(companyID)
	return o
}

// SetCompanyID adds the companyId to the get filed returns params
func (o *GetFiledReturnsParams) SetCompanyID(companyID int32) {
	o.CompanyID = companyID
}

// WithCountry adds the country to the get filed returns params
func (o *GetFiledReturnsParams) WithCountry(country *string) *GetFiledReturnsParams {
	o.SetCountry(country)
	return o
}

// SetCountry adds the country to the get filed returns params
func (o *GetFiledReturnsParams) SetCountry(country *string) {
	o.Country = country
}

// WithEndPeriodMonth adds the endPeriodMonth to the get filed returns params
func (o *GetFiledReturnsParams) WithEndPeriodMonth(endPeriodMonth *int32) *GetFiledReturnsParams {
	o.SetEndPeriodMonth(endPeriodMonth)
	return o
}

// SetEndPeriodMonth adds the endPeriodMonth to the get filed returns params
func (o *GetFiledReturnsParams) SetEndPeriodMonth(endPeriodMonth *int32) {
	o.EndPeriodMonth = endPeriodMonth
}

// WithEndPeriodYear adds the endPeriodYear to the get filed returns params
func (o *GetFiledReturnsParams) WithEndPeriodYear(endPeriodYear *int32) *GetFiledReturnsParams {
	o.SetEndPeriodYear(endPeriodYear)
	return o
}

// SetEndPeriodYear adds the endPeriodYear to the get filed returns params
func (o *GetFiledReturnsParams) SetEndPeriodYear(endPeriodYear *int32) {
	o.EndPeriodYear = endPeriodYear
}

// WithFilingCalendarID adds the filingCalendarID to the get filed returns params
func (o *GetFiledReturnsParams) WithFilingCalendarID(filingCalendarID *int64) *GetFiledReturnsParams {
	o.SetFilingCalendarID(filingCalendarID)
	return o
}

// SetFilingCalendarID adds the filingCalendarId to the get filed returns params
func (o *GetFiledReturnsParams) SetFilingCalendarID(filingCalendarID *int64) {
	o.FilingCalendarID = filingCalendarID
}

// WithFrequency adds the frequency to the get filed returns params
func (o *GetFiledReturnsParams) WithFrequency(frequency *string) *GetFiledReturnsParams {
	o.SetFrequency(frequency)
	return o
}

// SetFrequency adds the frequency to the get filed returns params
func (o *GetFiledReturnsParams) SetFrequency(frequency *string) {
	o.Frequency = frequency
}

// WithRegion adds the region to the get filed returns params
func (o *GetFiledReturnsParams) WithRegion(region *string) *GetFiledReturnsParams {
	o.SetRegion(region)
	return o
}

// SetRegion adds the region to the get filed returns params
func (o *GetFiledReturnsParams) SetRegion(region *string) {
	o.Region = region
}

// WithStatus adds the status to the get filed returns params
func (o *GetFiledReturnsParams) WithStatus(status *string) *GetFiledReturnsParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the get filed returns params
func (o *GetFiledReturnsParams) SetStatus(status *string) {
	o.Status = status
}

// WithTaxformCode adds the taxformCode to the get filed returns params
func (o *GetFiledReturnsParams) WithTaxformCode(taxformCode *string) *GetFiledReturnsParams {
	o.SetTaxformCode(taxformCode)
	return o
}

// SetTaxformCode adds the taxformCode to the get filed returns params
func (o *GetFiledReturnsParams) SetTaxformCode(taxformCode *string) {
	o.TaxformCode = taxformCode
}

// WriteToRequest writes these params to a swagger request
func (o *GetFiledReturnsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XAvalaraClient != nil {

		// header param X-Avalara-Client
		if err := r.SetHeaderParam("X-Avalara-Client", *o.XAvalaraClient); err != nil {
			return err
		}
	}

	// path param companyId
	if err := r.SetPathParam("companyId", swag.FormatInt32(o.CompanyID)); err != nil {
		return err
	}

	if o.Country != nil {

		// query param country
		var qrCountry string

		if o.Country != nil {
			qrCountry = *o.Country
		}
		qCountry := qrCountry
		if qCountry != "" {

			if err := r.SetQueryParam("country", qCountry); err != nil {
				return err
			}
		}
	}

	if o.EndPeriodMonth != nil {

		// query param endPeriodMonth
		var qrEndPeriodMonth int32

		if o.EndPeriodMonth != nil {
			qrEndPeriodMonth = *o.EndPeriodMonth
		}
		qEndPeriodMonth := swag.FormatInt32(qrEndPeriodMonth)
		if qEndPeriodMonth != "" {

			if err := r.SetQueryParam("endPeriodMonth", qEndPeriodMonth); err != nil {
				return err
			}
		}
	}

	if o.EndPeriodYear != nil {

		// query param endPeriodYear
		var qrEndPeriodYear int32

		if o.EndPeriodYear != nil {
			qrEndPeriodYear = *o.EndPeriodYear
		}
		qEndPeriodYear := swag.FormatInt32(qrEndPeriodYear)
		if qEndPeriodYear != "" {

			if err := r.SetQueryParam("endPeriodYear", qEndPeriodYear); err != nil {
				return err
			}
		}
	}

	if o.FilingCalendarID != nil {

		// query param filingCalendarId
		var qrFilingCalendarID int64

		if o.FilingCalendarID != nil {
			qrFilingCalendarID = *o.FilingCalendarID
		}
		qFilingCalendarID := swag.FormatInt64(qrFilingCalendarID)
		if qFilingCalendarID != "" {

			if err := r.SetQueryParam("filingCalendarId", qFilingCalendarID); err != nil {
				return err
			}
		}
	}

	if o.Frequency != nil {

		// query param frequency
		var qrFrequency string

		if o.Frequency != nil {
			qrFrequency = *o.Frequency
		}
		qFrequency := qrFrequency
		if qFrequency != "" {

			if err := r.SetQueryParam("frequency", qFrequency); err != nil {
				return err
			}
		}
	}

	if o.Region != nil {

		// query param region
		var qrRegion string

		if o.Region != nil {
			qrRegion = *o.Region
		}
		qRegion := qrRegion
		if qRegion != "" {

			if err := r.SetQueryParam("region", qRegion); err != nil {
				return err
			}
		}
	}

	if o.Status != nil {

		// query param status
		var qrStatus string

		if o.Status != nil {
			qrStatus = *o.Status
		}
		qStatus := qrStatus
		if qStatus != "" {

			if err := r.SetQueryParam("status", qStatus); err != nil {
				return err
			}
		}
	}

	if o.TaxformCode != nil {

		// query param taxformCode
		var qrTaxformCode string

		if o.TaxformCode != nil {
			qrTaxformCode = *o.TaxformCode
		}
		qTaxformCode := qrTaxformCode
		if qTaxformCode != "" {

			if err := r.SetQueryParam("taxformCode", qTaxformCode); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
