// Code generated by go-swagger; DO NOT EDIT.

package multi_document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/TomerHeber/avatax-v2-go/models"
)

// CommitMultiDocumentTransactionReader is a Reader for the CommitMultiDocumentTransaction structure.
type CommitMultiDocumentTransactionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CommitMultiDocumentTransactionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCommitMultiDocumentTransactionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCommitMultiDocumentTransactionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCommitMultiDocumentTransactionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCommitMultiDocumentTransactionOK creates a CommitMultiDocumentTransactionOK with default headers values
func NewCommitMultiDocumentTransactionOK() *CommitMultiDocumentTransactionOK {
	return &CommitMultiDocumentTransactionOK{}
}

/* CommitMultiDocumentTransactionOK describes a response with status code 200, with default header values.

Success
*/
type CommitMultiDocumentTransactionOK struct {
	Payload *models.MultiDocumentModel
}

func (o *CommitMultiDocumentTransactionOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/transactions/multidocument/commit][%d] commitMultiDocumentTransactionOK  %+v", 200, o.Payload)
}
func (o *CommitMultiDocumentTransactionOK) GetPayload() *models.MultiDocumentModel {
	return o.Payload
}

func (o *CommitMultiDocumentTransactionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MultiDocumentModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCommitMultiDocumentTransactionBadRequest creates a CommitMultiDocumentTransactionBadRequest with default headers values
func NewCommitMultiDocumentTransactionBadRequest() *CommitMultiDocumentTransactionBadRequest {
	return &CommitMultiDocumentTransactionBadRequest{}
}

/* CommitMultiDocumentTransactionBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CommitMultiDocumentTransactionBadRequest struct {
}

func (o *CommitMultiDocumentTransactionBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/transactions/multidocument/commit][%d] commitMultiDocumentTransactionBadRequest ", 400)
}

func (o *CommitMultiDocumentTransactionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCommitMultiDocumentTransactionUnauthorized creates a CommitMultiDocumentTransactionUnauthorized with default headers values
func NewCommitMultiDocumentTransactionUnauthorized() *CommitMultiDocumentTransactionUnauthorized {
	return &CommitMultiDocumentTransactionUnauthorized{}
}

/* CommitMultiDocumentTransactionUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CommitMultiDocumentTransactionUnauthorized struct {
}

func (o *CommitMultiDocumentTransactionUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v2/transactions/multidocument/commit][%d] commitMultiDocumentTransactionUnauthorized ", 401)
}

func (o *CommitMultiDocumentTransactionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
