// Code generated by go-swagger; DO NOT EDIT.

package multi_document

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMultiDocumentTransactionByCodeAndTypeParams creates a new GetMultiDocumentTransactionByCodeAndTypeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMultiDocumentTransactionByCodeAndTypeParams() *GetMultiDocumentTransactionByCodeAndTypeParams {
	return &GetMultiDocumentTransactionByCodeAndTypeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMultiDocumentTransactionByCodeAndTypeParamsWithTimeout creates a new GetMultiDocumentTransactionByCodeAndTypeParams object
// with the ability to set a timeout on a request.
func NewGetMultiDocumentTransactionByCodeAndTypeParamsWithTimeout(timeout time.Duration) *GetMultiDocumentTransactionByCodeAndTypeParams {
	return &GetMultiDocumentTransactionByCodeAndTypeParams{
		timeout: timeout,
	}
}

// NewGetMultiDocumentTransactionByCodeAndTypeParamsWithContext creates a new GetMultiDocumentTransactionByCodeAndTypeParams object
// with the ability to set a context for a request.
func NewGetMultiDocumentTransactionByCodeAndTypeParamsWithContext(ctx context.Context) *GetMultiDocumentTransactionByCodeAndTypeParams {
	return &GetMultiDocumentTransactionByCodeAndTypeParams{
		Context: ctx,
	}
}

// NewGetMultiDocumentTransactionByCodeAndTypeParamsWithHTTPClient creates a new GetMultiDocumentTransactionByCodeAndTypeParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMultiDocumentTransactionByCodeAndTypeParamsWithHTTPClient(client *http.Client) *GetMultiDocumentTransactionByCodeAndTypeParams {
	return &GetMultiDocumentTransactionByCodeAndTypeParams{
		HTTPClient: client,
	}
}

/* GetMultiDocumentTransactionByCodeAndTypeParams contains all the parameters to send to the API endpoint
   for the get multi document transaction by code and type operation.

   Typically these are written to a http.Request.
*/
type GetMultiDocumentTransactionByCodeAndTypeParams struct {

	/* DollarInclude.

	   Specifies objects to include in the response after transaction is created
	*/
	DollarInclude *string

	/* XAvalaraClient.

	   Identifies the software you are using to call this API.  For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/) .

	   Default: "Swagger UI; 21.12.0; Custom; 1.0"
	*/
	XAvalaraClient *string

	/* Code.

	   The multidocument code to retrieve
	*/
	Code string

	/* Type.

	   The transaction type to retrieve
	*/
	Type string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get multi document transaction by code and type params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMultiDocumentTransactionByCodeAndTypeParams) WithDefaults() *GetMultiDocumentTransactionByCodeAndTypeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get multi document transaction by code and type params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMultiDocumentTransactionByCodeAndTypeParams) SetDefaults() {
	var (
		xAvalaraClientDefault = string("Swagger UI; 21.12.0; Custom; 1.0")
	)

	val := GetMultiDocumentTransactionByCodeAndTypeParams{
		XAvalaraClient: &xAvalaraClientDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get multi document transaction by code and type params
func (o *GetMultiDocumentTransactionByCodeAndTypeParams) WithTimeout(timeout time.Duration) *GetMultiDocumentTransactionByCodeAndTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get multi document transaction by code and type params
func (o *GetMultiDocumentTransactionByCodeAndTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get multi document transaction by code and type params
func (o *GetMultiDocumentTransactionByCodeAndTypeParams) WithContext(ctx context.Context) *GetMultiDocumentTransactionByCodeAndTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get multi document transaction by code and type params
func (o *GetMultiDocumentTransactionByCodeAndTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get multi document transaction by code and type params
func (o *GetMultiDocumentTransactionByCodeAndTypeParams) WithHTTPClient(client *http.Client) *GetMultiDocumentTransactionByCodeAndTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get multi document transaction by code and type params
func (o *GetMultiDocumentTransactionByCodeAndTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDollarInclude adds the dollarInclude to the get multi document transaction by code and type params
func (o *GetMultiDocumentTransactionByCodeAndTypeParams) WithDollarInclude(dollarInclude *string) *GetMultiDocumentTransactionByCodeAndTypeParams {
	o.SetDollarInclude(dollarInclude)
	return o
}

// SetDollarInclude adds the dollarInclude to the get multi document transaction by code and type params
func (o *GetMultiDocumentTransactionByCodeAndTypeParams) SetDollarInclude(dollarInclude *string) {
	o.DollarInclude = dollarInclude
}

// WithXAvalaraClient adds the xAvalaraClient to the get multi document transaction by code and type params
func (o *GetMultiDocumentTransactionByCodeAndTypeParams) WithXAvalaraClient(xAvalaraClient *string) *GetMultiDocumentTransactionByCodeAndTypeParams {
	o.SetXAvalaraClient(xAvalaraClient)
	return o
}

// SetXAvalaraClient adds the xAvalaraClient to the get multi document transaction by code and type params
func (o *GetMultiDocumentTransactionByCodeAndTypeParams) SetXAvalaraClient(xAvalaraClient *string) {
	o.XAvalaraClient = xAvalaraClient
}

// WithCode adds the code to the get multi document transaction by code and type params
func (o *GetMultiDocumentTransactionByCodeAndTypeParams) WithCode(code string) *GetMultiDocumentTransactionByCodeAndTypeParams {
	o.SetCode(code)
	return o
}

// SetCode adds the code to the get multi document transaction by code and type params
func (o *GetMultiDocumentTransactionByCodeAndTypeParams) SetCode(code string) {
	o.Code = code
}

// WithType adds the typeVar to the get multi document transaction by code and type params
func (o *GetMultiDocumentTransactionByCodeAndTypeParams) WithType(typeVar string) *GetMultiDocumentTransactionByCodeAndTypeParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get multi document transaction by code and type params
func (o *GetMultiDocumentTransactionByCodeAndTypeParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetMultiDocumentTransactionByCodeAndTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DollarInclude != nil {

		// query param $include
		var qrDollarInclude string

		if o.DollarInclude != nil {
			qrDollarInclude = *o.DollarInclude
		}
		qDollarInclude := qrDollarInclude
		if qDollarInclude != "" {

			if err := r.SetQueryParam("$include", qDollarInclude); err != nil {
				return err
			}
		}
	}

	if o.XAvalaraClient != nil {

		// header param X-Avalara-Client
		if err := r.SetHeaderParam("X-Avalara-Client", *o.XAvalaraClient); err != nil {
			return err
		}
	}

	// path param code
	if err := r.SetPathParam("code", o.Code); err != nil {
		return err
	}

	// path param type
	if err := r.SetPathParam("type", o.Type); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
