// Code generated by go-swagger; DO NOT EDIT.

package nexus

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/TomerHeber/avatax-v2-go/models"
)

// UpdateNexusReader is a Reader for the UpdateNexus structure.
type UpdateNexusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateNexusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateNexusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateNexusBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateNexusUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateNexusNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateNexusOK creates a UpdateNexusOK with default headers values
func NewUpdateNexusOK() *UpdateNexusOK {
	return &UpdateNexusOK{}
}

/* UpdateNexusOK describes a response with status code 200, with default header values.

Success
*/
type UpdateNexusOK struct {
	Payload *models.NexusModel
}

func (o *UpdateNexusOK) Error() string {
	return fmt.Sprintf("[PUT /api/v2/companies/{companyId}/nexus/{id}][%d] updateNexusOK  %+v", 200, o.Payload)
}
func (o *UpdateNexusOK) GetPayload() *models.NexusModel {
	return o.Payload
}

func (o *UpdateNexusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NexusModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateNexusBadRequest creates a UpdateNexusBadRequest with default headers values
func NewUpdateNexusBadRequest() *UpdateNexusBadRequest {
	return &UpdateNexusBadRequest{}
}

/* UpdateNexusBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UpdateNexusBadRequest struct {
}

func (o *UpdateNexusBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/v2/companies/{companyId}/nexus/{id}][%d] updateNexusBadRequest ", 400)
}

func (o *UpdateNexusBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateNexusUnauthorized creates a UpdateNexusUnauthorized with default headers values
func NewUpdateNexusUnauthorized() *UpdateNexusUnauthorized {
	return &UpdateNexusUnauthorized{}
}

/* UpdateNexusUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type UpdateNexusUnauthorized struct {
}

func (o *UpdateNexusUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /api/v2/companies/{companyId}/nexus/{id}][%d] updateNexusUnauthorized ", 401)
}

func (o *UpdateNexusUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateNexusNotFound creates a UpdateNexusNotFound with default headers values
func NewUpdateNexusNotFound() *UpdateNexusNotFound {
	return &UpdateNexusNotFound{}
}

/* UpdateNexusNotFound describes a response with status code 404, with default header values.

Not Found
*/
type UpdateNexusNotFound struct {
}

func (o *UpdateNexusNotFound) Error() string {
	return fmt.Sprintf("[PUT /api/v2/companies/{companyId}/nexus/{id}][%d] updateNexusNotFound ", 404)
}

func (o *UpdateNexusNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
