// Code generated by go-swagger; DO NOT EDIT.

package companies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new companies API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for companies API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CertifyIntegration(params *CertifyIntegrationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CertifyIntegrationOK, error)

	ChangeFilingStatus(params *ChangeFilingStatusParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ChangeFilingStatusOK, error)

	CompanyInitialize(params *CompanyInitializeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CompanyInitializeOK, error)

	CreateCompanies(params *CreateCompaniesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateCompaniesOK, error)

	CreateCompanyParameters(params *CreateCompanyParametersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateCompanyParametersCreated, error)

	CreateFundingRequest(params *CreateFundingRequestParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateFundingRequestOK, error)

	DeleteCompany(params *DeleteCompanyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteCompanyOK, error)

	DeleteCompanyParameter(params *DeleteCompanyParameterParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteCompanyParameterOK, error)

	FundingConfigurationByCompany(params *FundingConfigurationByCompanyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*FundingConfigurationByCompanyOK, error)

	FundingConfigurationsByCompanyAndCurrency(params *FundingConfigurationsByCompanyAndCurrencyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*FundingConfigurationsByCompanyAndCurrencyOK, error)

	GetCompany(params *GetCompanyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCompanyOK, error)

	GetCompanyConfiguration(params *GetCompanyConfigurationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCompanyConfigurationOK, error)

	GetCompanyParameterDetail(params *GetCompanyParameterDetailParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCompanyParameterDetailOK, error)

	GetFilingStatus(params *GetFilingStatusParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetFilingStatusOK, error)

	ListCompanyParameterDetails(params *ListCompanyParameterDetailsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListCompanyParameterDetailsOK, error)

	ListFundingRequestsByCompany(params *ListFundingRequestsByCompanyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListFundingRequestsByCompanyOK, error)

	ListMrsCompanies(params *ListMrsCompaniesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListMrsCompaniesOK, error)

	QueryCompanies(params *QueryCompaniesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*QueryCompaniesOK, error)

	SetCompanyConfiguration(params *SetCompanyConfigurationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SetCompanyConfigurationOK, error)

	UpdateCompany(params *UpdateCompanyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateCompanyOK, error)

	UpdateCompanyParameterDetail(params *UpdateCompanyParameterDetailParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateCompanyParameterDetailOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CertifyIntegration checks whether the integration being used to set up this company and run transactions onto this company is compliant to all requirements

  Examines the most recent 100 transactions or data from the last month when verifying transaction-related integrations.
For partners who write integrations against AvaTax for many clients, this API is a way to do a quick self testing to verify whether the
written integrations for a company are sufficient enough to be delivered to the respective customers to start using it.

This API provides messages specific enough (through predefined checks) to guide the partner on what integrations are still missing from the company to get fully certified.
The API makes the following checks to conclude if the company is NOT fully certified:
1. Any past month items contains generic tax code of P0000000.
2. All the companies on the requesting account are test companies.
3. No Voided/Cancelled documents in the past 30 days.
4. There are less than 2 committed documents.
5. Any documentCode is a generic GUID string.
6. Any customerCode on document is a generic GUID string.
7. No document has more than 1 documentLine.
8. All of the documents have missing exemptionNo, customerUsageType, taxDateOverride or negative amount.
9. Any document quantity is a negative number.
10. Any document have repeated lines.
11. No document has shipping charge.
12. All documents have same ItemCodes, descriptions and taxCodes.
13. Less than 2 addresses used across all documents.
14. Whether locationCode was used in documents.
15. Account with AvaGlobal subscription and no documents have VATBuyerId.
16. Any document has currencyCode not being USD for accounts with AvaGlobal subscription.
17. All documents have countryCode used for accounts with AvaGlobal subscription.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, AccountOperator, AccountUser, CompanyAdmin, CompanyUser, Compliance Root User, ComplianceAdmin, ComplianceUser, CSPAdmin, CSPTester, FirmAdmin, FirmUser, ProStoresOperator, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.

*/
func (a *Client) CertifyIntegration(params *CertifyIntegrationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CertifyIntegrationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCertifyIntegrationParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CertifyIntegration",
		Method:             "GET",
		PathPattern:        "/api/v2/companies/{id}/certify",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CertifyIntegrationReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CertifyIntegrationOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for CertifyIntegration: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ChangeFilingStatus changes the filing status of this company

  Changes the current filing status of this company.

For customers using Avalara's Managed Returns Service, each company within their account can request
for Avalara to file tax returns on their behalf.  Avalara compliance team members will review all
requested filing calendars prior to beginning filing tax returns on behalf of this company.

The following changes may be requested through this API:

* If a company is in `NotYetFiling` status, the customer may request this be changed to `FilingRequested`.
* Avalara compliance team members may change a company from `FilingRequested` to `FirstFiling`.
* Avalara compliance team members may change a company from `FirstFiling` to `Active`.

All other status changes must be requested through the Avalara customer support team.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, AccountOperator, AccountUser, CompanyAdmin, CompanyUser, Compliance Root User, ComplianceAdmin, ComplianceUser, CSPAdmin, CSPTester, FirmAdmin, FirmUser, ProStoresOperator, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.

*/
func (a *Client) ChangeFilingStatus(params *ChangeFilingStatusParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ChangeFilingStatusOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewChangeFilingStatusParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ChangeFilingStatus",
		Method:             "POST",
		PathPattern:        "/api/v2/companies/{id}/filingstatus",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/*+json", "application/json", "application/json-patch+json", "text/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ChangeFilingStatusReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ChangeFilingStatusOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ChangeFilingStatus: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  CompanyInitialize quicks setup for a company with a single physical address

  Shortcut to quickly setup a single-physical-location company with critical information and activate it.
This API provides quick and simple company setup functionality and does the following things:

* Create a company object with its own tax profile
* Add a key contact person for the company
* Set up one physical location for the main office
* Declare nexus in all taxing jurisdictions for that main office address
* Activate the company

This API only provides a limited subset of functionality compared to the 'Create Company' API call.
If you need additional features or options not present in this 'Quick Setup' API call, please use the full 'Create Company' call instead.
Please allow 1 minute before making transactions using the company.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, CompanyAdmin, CSPTester, FirmAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.

*/
func (a *Client) CompanyInitialize(params *CompanyInitializeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CompanyInitializeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCompanyInitializeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CompanyInitialize",
		Method:             "POST",
		PathPattern:        "/api/v2/companies/initialize",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/*+json", "application/json", "application/json-patch+json", "text/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CompanyInitializeReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CompanyInitializeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for CompanyInitialize: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  CreateCompanies creates new companies

  Create one or more new company objects.
A 'company' represents a single corporation or individual that is registered to handle transactional taxes.
You may attach nested data objects such as contacts, locations, and nexus with this CREATE call, and those objects will be created with the company.

NOTE: Please do not use these blacklisted characters in company name and code: ';', '\', '|'.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, CompanyAdmin, CSPTester, FirmAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.

*/
func (a *Client) CreateCompanies(params *CreateCompaniesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateCompaniesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateCompaniesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateCompanies",
		Method:             "POST",
		PathPattern:        "/api/v2/companies",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/*+json", "application/json", "application/json-patch+json", "text/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateCompaniesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateCompaniesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for CreateCompanies: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  CreateCompanyParameters adds parameters to a company

  Add parameters to a company.

Some companies can be taxed and reported differently depending on the properties of the company, such as IsPrimaryAddress. In AvaTax, these tax-affecting properties are called "parameters".

A parameter added to a company will be used by default in tax calculation but will not show on the transaction line referencing the company.

A company location parameter specified on a transaction line will override a company parameter if they share the same parameter name.

To see available parameters for this company, call `/api/v2/definitions/parameters?$filter=attributeType eq Company`

Some parameters are only available for use if you have subscribed to specific AvaTax services. To see which parameters you are able to use, add the query parameter "$showSubscribed=true" to the parameter definition call above.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, CompanyAdmin, CSPTester, FirmAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.

*/
func (a *Client) CreateCompanyParameters(params *CreateCompanyParametersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateCompanyParametersCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateCompanyParametersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateCompanyParameters",
		Method:             "POST",
		PathPattern:        "/api/v2/companies/{companyId}/parameters",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/*+json", "application/json", "application/json-patch+json", "text/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateCompanyParametersReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateCompanyParametersCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for CreateCompanyParameters: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  CreateFundingRequest requests managed returns funding setup for a company

  This API is available by invitation only.
Companies that use the Avalara Managed Returns or the SST Certified Service Provider services are
required to setup their funding configuration before Avalara can begin filing tax returns on their
behalf.
Funding configuration for each company is set up by submitting a funding setup request, which can
be sent either via email or via an embedded HTML widget.
When the funding configuration is submitted to Avalara, it will be reviewed by treasury team members
before approval.
This API records that an ambedded HTML funding setup widget was activated.
This API requires a subscription to Avalara Managed Returns or SST Certified Service Provider.

### Security Policies

* This API depends on the following active services:*Returns* (at least one of):  Mrs, MRSComplianceManager, AvaTaxCsp.
* This API requires one of the following user roles: AccountAdmin, AccountOperator, AccountUser, CompanyAdmin, CompanyUser, Compliance Root User, ComplianceAdmin, ComplianceUser, CSPAdmin, CSPTester, FirmAdmin, FirmUser, ProStoresOperator, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.

*/
func (a *Client) CreateFundingRequest(params *CreateFundingRequestParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateFundingRequestOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateFundingRequestParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateFundingRequest",
		Method:             "POST",
		PathPattern:        "/api/v2/companies/{id}/funding/setup",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/*+json", "application/json", "application/json-patch+json", "text/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateFundingRequestReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateFundingRequestOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for CreateFundingRequest: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DeleteCompany deletes a single company

  Deleting a company will delete all child companies, and all users attached to this company.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, CompanyAdmin, CSPTester, FirmAdmin, SSTAdmin, TechnicalSupportAdmin.

*/
func (a *Client) DeleteCompany(params *DeleteCompanyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteCompanyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteCompanyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteCompany",
		Method:             "DELETE",
		PathPattern:        "/api/v2/companies/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteCompanyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteCompanyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteCompany: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DeleteCompanyParameter deletes a single company parameter

  Delete a parameter of a company.
Some companies can be taxed and reported differently depending on the properties of the company, such as IsPrimaryAddress. In AvaTax, these tax-affecting properties are called "parameters".

A parameter added to a company will be used by default in tax calculation but will not show on the transaction line referencing the company.

A company location parameter specified on a transaction line will override a company parameter if they share the same parameter name.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, CompanyAdmin, CSPTester, FirmAdmin, SSTAdmin, TechnicalSupportAdmin.

*/
func (a *Client) DeleteCompanyParameter(params *DeleteCompanyParameterParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteCompanyParameterOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteCompanyParameterParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteCompanyParameter",
		Method:             "DELETE",
		PathPattern:        "/api/v2/companies/{companyId}/parameters/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteCompanyParameterReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteCompanyParameterOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteCompanyParameter: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  FundingConfigurationByCompany checks the funding configuration of a company

  This API is available by invitation only.
Requires a subscription to Avalara Managed Returns or SST Certified Service Provider.
Returns the funding configuration of the requested company.
.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, AccountOperator, AccountUser, CompanyAdmin, CompanyUser, Compliance Root User, ComplianceAdmin, ComplianceUser, CSPAdmin, CSPTester, FirmAdmin, FirmUser, ProStoresOperator, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.
* This API depends on the following active services:*Returns* (at least one of):  Mrs, MRSComplianceManager, AvaTaxCsp.*Firm Managed* (for accounts managed by a firm):  ARA, ARAManaged.

*/
func (a *Client) FundingConfigurationByCompany(params *FundingConfigurationByCompanyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*FundingConfigurationByCompanyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewFundingConfigurationByCompanyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "FundingConfigurationByCompany",
		Method:             "GET",
		PathPattern:        "/api/v2/companies/{companyId}/funding/configuration",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &FundingConfigurationByCompanyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*FundingConfigurationByCompanyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for FundingConfigurationByCompany: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  FundingConfigurationsByCompanyAndCurrency checks the funding configuration of a company

  This API is available by invitation only.
Requires a subscription to Avalara Managed Returns or SST Certified Service Provider.
Returns the funding configuration of the requested company.
.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, AccountOperator, AccountUser, CompanyAdmin, CompanyUser, Compliance Root User, ComplianceAdmin, ComplianceUser, CSPAdmin, CSPTester, FirmAdmin, FirmUser, ProStoresOperator, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.
* This API depends on the following active services:*Returns* (at least one of):  Mrs, MRSComplianceManager, AvaTaxCsp.*Firm Managed* (for accounts managed by a firm):  ARA, ARAManaged.

*/
func (a *Client) FundingConfigurationsByCompanyAndCurrency(params *FundingConfigurationsByCompanyAndCurrencyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*FundingConfigurationsByCompanyAndCurrencyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewFundingConfigurationsByCompanyAndCurrencyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "FundingConfigurationsByCompanyAndCurrency",
		Method:             "GET",
		PathPattern:        "/api/v2/companies/{companyId}/funding/configurations",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &FundingConfigurationsByCompanyAndCurrencyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*FundingConfigurationsByCompanyAndCurrencyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for FundingConfigurationsByCompanyAndCurrency: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetCompany retrieves a single company

  Get the company object identified by this URL.
A 'company' represents a single corporation or individual that is registered to handle transactional taxes.
You may specify one or more of the following values in the '$include' parameter to fetch additional nested data, using commas to separate multiple values:

 * Contacts
 * Items
 * Locations
 * Nexus
 * Settings
 * TaxCodes
 * TaxRules
 * UPC
 * Parameters

### Security Policies

* This API requires one of the following user roles: AccountAdmin, AccountOperator, AccountUser, CompanyAdmin, CompanyUser, Compliance Root User, ComplianceAdmin, ComplianceUser, CSPAdmin, CSPTester, FirmAdmin, FirmUser, ProStoresOperator, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.

*/
func (a *Client) GetCompany(params *GetCompanyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCompanyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCompanyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetCompany",
		Method:             "GET",
		PathPattern:        "/api/v2/companies/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetCompanyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCompanyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCompany: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetCompanyConfiguration gets configuration settings for this company

  Retrieve a list of all configuration settings tied to this company.

Configuration settings provide you with the ability to control features of your account and of your
tax software.  The category name `AvaCertServiceConfig` is reserved for
Avalara internal software configuration values; to store your own company-level settings, please
create a new category name that begins with `X-`, for example, `X-MyCustomCategory`.

Company settings are permanent settings that cannot be deleted.  You can set the value of a
company setting to null if desired and if the particular setting supports it.

Avalara-based company settings for `AvaCertServiceConfig` affect your company's exemption certificate
processing, and should be changed with care.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, AccountUser, CompanyAdmin, CompanyUser, CSPAdmin, CSPTester, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser.

*/
func (a *Client) GetCompanyConfiguration(params *GetCompanyConfigurationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCompanyConfigurationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCompanyConfigurationParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetCompanyConfiguration",
		Method:             "GET",
		PathPattern:        "/api/v2/companies/{id}/configuration",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetCompanyConfigurationReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCompanyConfigurationOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCompanyConfiguration: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetCompanyParameterDetail retrieves a single company parameter

  Retrieves a single parameter of a company.

Some companies can be taxed and reported differently depending on the properties of the company, such as IsPrimaryAddress. In AvaTax, these tax-affecting properties are called "parameters".

A parameter added to a company will be used by default in tax calculation but will not show on the transaction line referencing the company.

A company location parameter specified on a transaction line will override a company parameter if they share the same parameter name.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, AccountOperator, AccountUser, CompanyAdmin, CompanyUser, Compliance Root User, ComplianceAdmin, ComplianceUser, CSPAdmin, CSPTester, FirmAdmin, FirmUser, ProStoresOperator, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.

*/
func (a *Client) GetCompanyParameterDetail(params *GetCompanyParameterDetailParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCompanyParameterDetailOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCompanyParameterDetailParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetCompanyParameterDetail",
		Method:             "GET",
		PathPattern:        "/api/v2/companies/{companyId}/parameters/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetCompanyParameterDetailReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCompanyParameterDetailOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCompanyParameterDetail: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetFilingStatus gets this company s filing status

  Retrieve the current filing status of this company.

For customers using Avalara's Managed Returns Service, each company within their account can request
for Avalara to file tax returns on their behalf.  Avalara compliance team members will review all
requested filing calendars prior to beginning filing tax returns on behalf of this company.

A company's filing status can be one of the following values:

* `NoReporting` - This company is not configured to report tax returns; instead, it reports through a parent company.
* `NotYetFiling` - This company has not yet begun filing tax returns through Avalara's Managed Returns Service.
* `FilingRequested` - The company has requested to begin filing tax returns, but Avalara's compliance team has not yet begun filing.
* `FirstFiling` - The company has recently filing tax returns and is in a new status.
* `Active` - The company is currently active and is filing tax returns via Avalara Managed Returns.
* `Inactive` - The company is currently inactive.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, AccountOperator, AccountUser, CompanyAdmin, CompanyUser, Compliance Root User, ComplianceAdmin, ComplianceUser, CSPAdmin, CSPTester, FirmAdmin, FirmUser, ProStoresOperator, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.

*/
func (a *Client) GetFilingStatus(params *GetFilingStatusParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetFilingStatusOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetFilingStatusParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetFilingStatus",
		Method:             "GET",
		PathPattern:        "/api/v2/companies/{id}/filingstatus",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetFilingStatusReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetFilingStatusOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetFilingStatus: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ListCompanyParameterDetails retrieves parameters for a company

  Retrieve all parameters of a company.

Some companies can be taxed and reported differently depending on the properties of the company, such as IsPrimaryAddress. In AvaTax, these tax-affecting properties are called "parameters".

A parameter added to a company will be used by default in tax calculation but will not show on the transaction line referencing the company.

A company location parameter specified on a transaction line will override a company parameter if they share the same parameter name.

Search for specific objects using the criteria in the `$filter` parameter; full documentation is available on [Filtering in REST](http://developer.avalara.com/avatax/filtering-in-rest/) .
Paginate your results using the `$top`, `$skip`, and `$orderby` parameters.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, AccountOperator, AccountUser, CompanyAdmin, CompanyUser, Compliance Root User, ComplianceAdmin, ComplianceUser, CSPAdmin, CSPTester, FirmAdmin, FirmUser, ProStoresOperator, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.

*/
func (a *Client) ListCompanyParameterDetails(params *ListCompanyParameterDetailsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListCompanyParameterDetailsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListCompanyParameterDetailsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListCompanyParameterDetails",
		Method:             "GET",
		PathPattern:        "/api/v2/companies/{companyId}/parameters",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListCompanyParameterDetailsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListCompanyParameterDetailsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ListCompanyParameterDetails: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ListFundingRequestsByCompany checks managed returns funding status for a company

  This API is available by invitation only.
Requires a subscription to Avalara Managed Returns or SST Certified Service Provider.
Returns a list of funding setup requests and their current status.
Each object in the result is a request that was made to setup or adjust funding status for this company.

### Security Policies

* This API depends on the following active services:*Returns* (at least one of):  Mrs, MRSComplianceManager, AvaTaxCsp.
* This API requires one of the following user roles: AccountAdmin, AccountOperator, AccountUser, CompanyAdmin, CompanyUser, Compliance Root User, ComplianceAdmin, ComplianceUser, CSPAdmin, CSPTester, FirmAdmin, FirmUser, ProStoresOperator, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.

*/
func (a *Client) ListFundingRequestsByCompany(params *ListFundingRequestsByCompanyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListFundingRequestsByCompanyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListFundingRequestsByCompanyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListFundingRequestsByCompany",
		Method:             "GET",
		PathPattern:        "/api/v2/companies/{id}/funding",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListFundingRequestsByCompanyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListFundingRequestsByCompanyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ListFundingRequestsByCompany: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ListMrsCompanies retrieves a list of m r s companies with account

  This API is available by invitation only.

Get a list of companies with an active MRS service.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, AccountOperator, AccountUser, CompanyAdmin, CompanyUser, Compliance Root User, ComplianceAdmin, ComplianceUser, CSPAdmin, CSPTester, FirmAdmin, FirmUser, ProStoresOperator, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.

*/
func (a *Client) ListMrsCompanies(params *ListMrsCompaniesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListMrsCompaniesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListMrsCompaniesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListMrsCompanies",
		Method:             "GET",
		PathPattern:        "/api/v2/companies/mrs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListMrsCompaniesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListMrsCompaniesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ListMrsCompanies: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  QueryCompanies retrieves all companies

  Get multiple company objects.

A `company` represents a single corporation or individual that is registered to handle transactional taxes.

Search for specific objects using the criteria in the `$filter` parameter; full documentation is available on [Filtering in REST](http://developer.avalara.com/avatax/filtering-in-rest/) .
Paginate your results using the `$top`, `$skip`, and `$orderby` parameters.
You may specify one or more of the following values in the `$include` parameter to fetch additional nested data, using commas to separate multiple values:

* Contacts
* Items
* Locations
* Nexus
* Settings
* TaxCodes
* TaxRules
* UPC
* Parameters

### Security Policies

* This API requires one of the following user roles: AccountAdmin, AccountOperator, AccountUser, CompanyAdmin, CompanyUser, Compliance Root User, ComplianceAdmin, ComplianceUser, CSPAdmin, CSPTester, FirmAdmin, FirmUser, ProStoresOperator, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.

*/
func (a *Client) QueryCompanies(params *QueryCompaniesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*QueryCompaniesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewQueryCompaniesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "QueryCompanies",
		Method:             "GET",
		PathPattern:        "/api/v2/companies",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &QueryCompaniesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*QueryCompaniesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for QueryCompanies: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  SetCompanyConfiguration changes configuration settings for this company

  Update configuration settings tied to this company.

Configuration settings provide you with the ability to control features of your account and of your
tax software.  The category names `AvaCertServiceConfig` is reserved for
Avalara internal software configuration values; to store your own company-level settings, please
create a new category name that begins with `X-`, for example, `X-MyCustomCategory`.

Company settings are permanent settings that cannot be deleted.  You can set the value of a
company setting to null if desired and if the particular setting supports it.

Avalara-based company settings for `AvaCertServiceConfig` affect your company's exemption certificate
processing, and should be changed with care.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, CompanyAdmin, CSPTester, SSTAdmin, TechnicalSupportAdmin.

*/
func (a *Client) SetCompanyConfiguration(params *SetCompanyConfigurationParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SetCompanyConfigurationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSetCompanyConfigurationParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "SetCompanyConfiguration",
		Method:             "POST",
		PathPattern:        "/api/v2/companies/{id}/configuration",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/*+json", "application/json", "application/json-patch+json", "text/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SetCompanyConfigurationReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SetCompanyConfigurationOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for SetCompanyConfiguration: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  UpdateCompany updates a single company

  Replace the existing company object at this URL with an updated object.

A `CompanyModel` represents a single corporation or individual that is registered to handle transactional taxes.
All data from the existing object will be replaced with data in the object you PUT.

When calling `UpdateCompany`, you are permitted to update the company itself.  Updates to the nested objects
such as contacts, locations, or settings are not permitted.  To update the nested objects

To set a field's value to `null`, you may either set its value to `null` or omit that field from the object you PUT.

NOTE: Please do not use these blacklisted characters in company name and code: ';', '\', '|'.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, CompanyAdmin, CSPTester, FirmAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.

*/
func (a *Client) UpdateCompany(params *UpdateCompanyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateCompanyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateCompanyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "UpdateCompany",
		Method:             "PUT",
		PathPattern:        "/api/v2/companies/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/*+json", "application/json", "application/json-patch+json", "text/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UpdateCompanyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateCompanyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for UpdateCompany: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  UpdateCompanyParameterDetail updates a company parameter

  Update a parameter of a company.

Some companies can be taxed and reported differently depending on the properties of the company, such as IsPrimaryAddress. In AvaTax, these tax-affecting properties are called "parameters".

A parameter added to a company will be used by default in tax calculation but will not show on the transaction line referencing the company.

A company location parameter specified on a transaction line will override a company parameter if they share the same parameter name.

### Security Policies

* This API requires one of the following user roles: AccountAdmin, CompanyAdmin, CSPTester, FirmAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.

*/
func (a *Client) UpdateCompanyParameterDetail(params *UpdateCompanyParameterDetailParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateCompanyParameterDetailOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateCompanyParameterDetailParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "UpdateCompanyParameterDetail",
		Method:             "PUT",
		PathPattern:        "/api/v2/companies/{companyId}/parameters/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/*+json", "application/json", "application/json-patch+json", "text/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UpdateCompanyParameterDetailReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateCompanyParameterDetailOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for UpdateCompanyParameterDetail: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
