// Code generated by go-swagger; DO NOT EDIT.

package companies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/TomerHeber/avatax-v2-go/models"
)

// CreateCompaniesReader is a Reader for the CreateCompanies structure.
type CreateCompaniesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCompaniesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateCompaniesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateCompaniesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateCompaniesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateCompaniesOK creates a CreateCompaniesOK with default headers values
func NewCreateCompaniesOK() *CreateCompaniesOK {
	return &CreateCompaniesOK{}
}

/* CreateCompaniesOK describes a response with status code 200, with default header values.

Success
*/
type CreateCompaniesOK struct {
	Payload []*models.CompanyModel
}

func (o *CreateCompaniesOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/companies][%d] createCompaniesOK  %+v", 200, o.Payload)
}
func (o *CreateCompaniesOK) GetPayload() []*models.CompanyModel {
	return o.Payload
}

func (o *CreateCompaniesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCompaniesBadRequest creates a CreateCompaniesBadRequest with default headers values
func NewCreateCompaniesBadRequest() *CreateCompaniesBadRequest {
	return &CreateCompaniesBadRequest{}
}

/* CreateCompaniesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateCompaniesBadRequest struct {
}

func (o *CreateCompaniesBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/companies][%d] createCompaniesBadRequest ", 400)
}

func (o *CreateCompaniesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateCompaniesUnauthorized creates a CreateCompaniesUnauthorized with default headers values
func NewCreateCompaniesUnauthorized() *CreateCompaniesUnauthorized {
	return &CreateCompaniesUnauthorized{}
}

/* CreateCompaniesUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateCompaniesUnauthorized struct {
}

func (o *CreateCompaniesUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v2/companies][%d] createCompaniesUnauthorized ", 401)
}

func (o *CreateCompaniesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
