// Code generated by go-swagger; DO NOT EDIT.

package companies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/TomerHeber/avatax-v2-go/models"
)

// NewUpdateCompanyParameterDetailParams creates a new UpdateCompanyParameterDetailParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateCompanyParameterDetailParams() *UpdateCompanyParameterDetailParams {
	return &UpdateCompanyParameterDetailParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateCompanyParameterDetailParamsWithTimeout creates a new UpdateCompanyParameterDetailParams object
// with the ability to set a timeout on a request.
func NewUpdateCompanyParameterDetailParamsWithTimeout(timeout time.Duration) *UpdateCompanyParameterDetailParams {
	return &UpdateCompanyParameterDetailParams{
		timeout: timeout,
	}
}

// NewUpdateCompanyParameterDetailParamsWithContext creates a new UpdateCompanyParameterDetailParams object
// with the ability to set a context for a request.
func NewUpdateCompanyParameterDetailParamsWithContext(ctx context.Context) *UpdateCompanyParameterDetailParams {
	return &UpdateCompanyParameterDetailParams{
		Context: ctx,
	}
}

// NewUpdateCompanyParameterDetailParamsWithHTTPClient creates a new UpdateCompanyParameterDetailParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateCompanyParameterDetailParamsWithHTTPClient(client *http.Client) *UpdateCompanyParameterDetailParams {
	return &UpdateCompanyParameterDetailParams{
		HTTPClient: client,
	}
}

/* UpdateCompanyParameterDetailParams contains all the parameters to send to the API endpoint
   for the update company parameter detail operation.

   Typically these are written to a http.Request.
*/
type UpdateCompanyParameterDetailParams struct {

	/* XAvalaraClient.

	   Identifies the software you are using to call this API.  For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/) .

	   Default: "Swagger UI; 21.12.0; Custom; 1.0"
	*/
	XAvalaraClient *string

	/* Body.

	   The company parameter object you wish to update.
	*/
	Body *models.CompanyParameterDetailModel

	/* CompanyID.

	   The company id.

	   Format: int32
	*/
	CompanyID int32

	/* ID.

	   The company parameter id

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update company parameter detail params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateCompanyParameterDetailParams) WithDefaults() *UpdateCompanyParameterDetailParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update company parameter detail params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateCompanyParameterDetailParams) SetDefaults() {
	var (
		xAvalaraClientDefault = string("Swagger UI; 21.12.0; Custom; 1.0")
	)

	val := UpdateCompanyParameterDetailParams{
		XAvalaraClient: &xAvalaraClientDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the update company parameter detail params
func (o *UpdateCompanyParameterDetailParams) WithTimeout(timeout time.Duration) *UpdateCompanyParameterDetailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update company parameter detail params
func (o *UpdateCompanyParameterDetailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update company parameter detail params
func (o *UpdateCompanyParameterDetailParams) WithContext(ctx context.Context) *UpdateCompanyParameterDetailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update company parameter detail params
func (o *UpdateCompanyParameterDetailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update company parameter detail params
func (o *UpdateCompanyParameterDetailParams) WithHTTPClient(client *http.Client) *UpdateCompanyParameterDetailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update company parameter detail params
func (o *UpdateCompanyParameterDetailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAvalaraClient adds the xAvalaraClient to the update company parameter detail params
func (o *UpdateCompanyParameterDetailParams) WithXAvalaraClient(xAvalaraClient *string) *UpdateCompanyParameterDetailParams {
	o.SetXAvalaraClient(xAvalaraClient)
	return o
}

// SetXAvalaraClient adds the xAvalaraClient to the update company parameter detail params
func (o *UpdateCompanyParameterDetailParams) SetXAvalaraClient(xAvalaraClient *string) {
	o.XAvalaraClient = xAvalaraClient
}

// WithBody adds the body to the update company parameter detail params
func (o *UpdateCompanyParameterDetailParams) WithBody(body *models.CompanyParameterDetailModel) *UpdateCompanyParameterDetailParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update company parameter detail params
func (o *UpdateCompanyParameterDetailParams) SetBody(body *models.CompanyParameterDetailModel) {
	o.Body = body
}

// WithCompanyID adds the companyID to the update company parameter detail params
func (o *UpdateCompanyParameterDetailParams) WithCompanyID(companyID int32) *UpdateCompanyParameterDetailParams {
	o.SetCompanyID(companyID)
	return o
}

// SetCompanyID adds the companyId to the update company parameter detail params
func (o *UpdateCompanyParameterDetailParams) SetCompanyID(companyID int32) {
	o.CompanyID = companyID
}

// WithID adds the id to the update company parameter detail params
func (o *UpdateCompanyParameterDetailParams) WithID(id int64) *UpdateCompanyParameterDetailParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update company parameter detail params
func (o *UpdateCompanyParameterDetailParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateCompanyParameterDetailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XAvalaraClient != nil {

		// header param X-Avalara-Client
		if err := r.SetHeaderParam("X-Avalara-Client", *o.XAvalaraClient); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param companyId
	if err := r.SetPathParam("companyId", swag.FormatInt32(o.CompanyID)); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
