// Code generated by go-swagger; DO NOT EDIT.

package companies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/TomerHeber/avatax-v2-go/models"
)

// UpdateCompanyReader is a Reader for the UpdateCompany structure.
type UpdateCompanyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateCompanyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateCompanyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateCompanyBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateCompanyUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateCompanyNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateCompanyOK creates a UpdateCompanyOK with default headers values
func NewUpdateCompanyOK() *UpdateCompanyOK {
	return &UpdateCompanyOK{}
}

/* UpdateCompanyOK describes a response with status code 200, with default header values.

Success
*/
type UpdateCompanyOK struct {
	Payload *models.CompanyModel
}

func (o *UpdateCompanyOK) Error() string {
	return fmt.Sprintf("[PUT /api/v2/companies/{id}][%d] updateCompanyOK  %+v", 200, o.Payload)
}
func (o *UpdateCompanyOK) GetPayload() *models.CompanyModel {
	return o.Payload
}

func (o *UpdateCompanyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CompanyModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateCompanyBadRequest creates a UpdateCompanyBadRequest with default headers values
func NewUpdateCompanyBadRequest() *UpdateCompanyBadRequest {
	return &UpdateCompanyBadRequest{}
}

/* UpdateCompanyBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UpdateCompanyBadRequest struct {
}

func (o *UpdateCompanyBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/v2/companies/{id}][%d] updateCompanyBadRequest ", 400)
}

func (o *UpdateCompanyBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateCompanyUnauthorized creates a UpdateCompanyUnauthorized with default headers values
func NewUpdateCompanyUnauthorized() *UpdateCompanyUnauthorized {
	return &UpdateCompanyUnauthorized{}
}

/* UpdateCompanyUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type UpdateCompanyUnauthorized struct {
}

func (o *UpdateCompanyUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /api/v2/companies/{id}][%d] updateCompanyUnauthorized ", 401)
}

func (o *UpdateCompanyUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateCompanyNotFound creates a UpdateCompanyNotFound with default headers values
func NewUpdateCompanyNotFound() *UpdateCompanyNotFound {
	return &UpdateCompanyNotFound{}
}

/* UpdateCompanyNotFound describes a response with status code 404, with default header values.

Not Found
*/
type UpdateCompanyNotFound struct {
}

func (o *UpdateCompanyNotFound) Error() string {
	return fmt.Sprintf("[PUT /api/v2/companies/{id}][%d] updateCompanyNotFound ", 404)
}

func (o *UpdateCompanyNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
