// Code generated by go-swagger; DO NOT EDIT.

package batches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/TomerHeber/avatax-v2-go/models"
)

// GetBatchReader is a Reader for the GetBatch structure.
type GetBatchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBatchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBatchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetBatchBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetBatchUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetBatchNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetBatchOK creates a GetBatchOK with default headers values
func NewGetBatchOK() *GetBatchOK {
	return &GetBatchOK{}
}

/* GetBatchOK describes a response with status code 200, with default header values.

Success
*/
type GetBatchOK struct {
	Payload *models.BatchModel
}

func (o *GetBatchOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/companies/{companyId}/batches/{id}][%d] getBatchOK  %+v", 200, o.Payload)
}
func (o *GetBatchOK) GetPayload() *models.BatchModel {
	return o.Payload
}

func (o *GetBatchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BatchModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBatchBadRequest creates a GetBatchBadRequest with default headers values
func NewGetBatchBadRequest() *GetBatchBadRequest {
	return &GetBatchBadRequest{}
}

/* GetBatchBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetBatchBadRequest struct {
}

func (o *GetBatchBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/companies/{companyId}/batches/{id}][%d] getBatchBadRequest ", 400)
}

func (o *GetBatchBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetBatchUnauthorized creates a GetBatchUnauthorized with default headers values
func NewGetBatchUnauthorized() *GetBatchUnauthorized {
	return &GetBatchUnauthorized{}
}

/* GetBatchUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetBatchUnauthorized struct {
}

func (o *GetBatchUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v2/companies/{companyId}/batches/{id}][%d] getBatchUnauthorized ", 401)
}

func (o *GetBatchUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetBatchNotFound creates a GetBatchNotFound with default headers values
func NewGetBatchNotFound() *GetBatchNotFound {
	return &GetBatchNotFound{}
}

/* GetBatchNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetBatchNotFound struct {
}

func (o *GetBatchNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v2/companies/{companyId}/batches/{id}][%d] getBatchNotFound ", 404)
}

func (o *GetBatchNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
