// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewAuditAccountParams creates a new AuditAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAuditAccountParams() *AuditAccountParams {
	return &AuditAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAuditAccountParamsWithTimeout creates a new AuditAccountParams object
// with the ability to set a timeout on a request.
func NewAuditAccountParamsWithTimeout(timeout time.Duration) *AuditAccountParams {
	return &AuditAccountParams{
		timeout: timeout,
	}
}

// NewAuditAccountParamsWithContext creates a new AuditAccountParams object
// with the ability to set a context for a request.
func NewAuditAccountParamsWithContext(ctx context.Context) *AuditAccountParams {
	return &AuditAccountParams{
		Context: ctx,
	}
}

// NewAuditAccountParamsWithHTTPClient creates a new AuditAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewAuditAccountParamsWithHTTPClient(client *http.Client) *AuditAccountParams {
	return &AuditAccountParams{
		HTTPClient: client,
	}
}

/* AuditAccountParams contains all the parameters to send to the API endpoint
   for the audit account operation.

   Typically these are written to a http.Request.
*/
type AuditAccountParams struct {

	/* DollarSkip.

	   If nonzero, skip this number of results before returning data.  Used with `$top` to provide pagination for large datasets.

	   Format: int32
	*/
	DollarSkip *int32

	/* DollarTop.

	   If nonzero, return no more than this number of results.  Used with `$skip` to provide pagination for large datasets.  Unless otherwise specified, the maximum number of records that can be returned from an API call is 1,000 records.

	   Format: int32
	   Default: 10
	*/
	DollarTop *int32

	/* XAvalaraClient.

	   Identifies the software you are using to call this API.  For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/) .

	   Default: "Swagger UI; 21.12.0; Custom; 1.0"
	*/
	XAvalaraClient *string

	/* End.

	   The end datetime of audit history you with to retrieve, e.g. "2018-06-08T17:15:00Z. Defaults to the current time. Maximum of an hour after the start time.

	   Format: date-time
	*/
	End *strfmt.DateTime

	/* ID.

	   The ID of the account you wish to audit.

	   Format: int32
	*/
	ID int32

	/* Start.

	   The start datetime of audit history you with to retrieve, e.g. "2018-06-08T17:00:00Z". Defaults to the past 15 minutes.

	   Format: date-time
	*/
	Start *strfmt.DateTime

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the audit account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuditAccountParams) WithDefaults() *AuditAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the audit account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuditAccountParams) SetDefaults() {
	var (
		dollarSkipDefault = int32(0)

		dollarTopDefault = int32(10)

		xAvalaraClientDefault = string("Swagger UI; 21.12.0; Custom; 1.0")
	)

	val := AuditAccountParams{
		DollarSkip:     &dollarSkipDefault,
		DollarTop:      &dollarTopDefault,
		XAvalaraClient: &xAvalaraClientDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the audit account params
func (o *AuditAccountParams) WithTimeout(timeout time.Duration) *AuditAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the audit account params
func (o *AuditAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the audit account params
func (o *AuditAccountParams) WithContext(ctx context.Context) *AuditAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the audit account params
func (o *AuditAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the audit account params
func (o *AuditAccountParams) WithHTTPClient(client *http.Client) *AuditAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the audit account params
func (o *AuditAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDollarSkip adds the dollarSkip to the audit account params
func (o *AuditAccountParams) WithDollarSkip(dollarSkip *int32) *AuditAccountParams {
	o.SetDollarSkip(dollarSkip)
	return o
}

// SetDollarSkip adds the dollarSkip to the audit account params
func (o *AuditAccountParams) SetDollarSkip(dollarSkip *int32) {
	o.DollarSkip = dollarSkip
}

// WithDollarTop adds the dollarTop to the audit account params
func (o *AuditAccountParams) WithDollarTop(dollarTop *int32) *AuditAccountParams {
	o.SetDollarTop(dollarTop)
	return o
}

// SetDollarTop adds the dollarTop to the audit account params
func (o *AuditAccountParams) SetDollarTop(dollarTop *int32) {
	o.DollarTop = dollarTop
}

// WithXAvalaraClient adds the xAvalaraClient to the audit account params
func (o *AuditAccountParams) WithXAvalaraClient(xAvalaraClient *string) *AuditAccountParams {
	o.SetXAvalaraClient(xAvalaraClient)
	return o
}

// SetXAvalaraClient adds the xAvalaraClient to the audit account params
func (o *AuditAccountParams) SetXAvalaraClient(xAvalaraClient *string) {
	o.XAvalaraClient = xAvalaraClient
}

// WithEnd adds the end to the audit account params
func (o *AuditAccountParams) WithEnd(end *strfmt.DateTime) *AuditAccountParams {
	o.SetEnd(end)
	return o
}

// SetEnd adds the end to the audit account params
func (o *AuditAccountParams) SetEnd(end *strfmt.DateTime) {
	o.End = end
}

// WithID adds the id to the audit account params
func (o *AuditAccountParams) WithID(id int32) *AuditAccountParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the audit account params
func (o *AuditAccountParams) SetID(id int32) {
	o.ID = id
}

// WithStart adds the start to the audit account params
func (o *AuditAccountParams) WithStart(start *strfmt.DateTime) *AuditAccountParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the audit account params
func (o *AuditAccountParams) SetStart(start *strfmt.DateTime) {
	o.Start = start
}

// WriteToRequest writes these params to a swagger request
func (o *AuditAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DollarSkip != nil {

		// query param $skip
		var qrDollarSkip int32

		if o.DollarSkip != nil {
			qrDollarSkip = *o.DollarSkip
		}
		qDollarSkip := swag.FormatInt32(qrDollarSkip)
		if qDollarSkip != "" {

			if err := r.SetQueryParam("$skip", qDollarSkip); err != nil {
				return err
			}
		}
	}

	if o.DollarTop != nil {

		// query param $top
		var qrDollarTop int32

		if o.DollarTop != nil {
			qrDollarTop = *o.DollarTop
		}
		qDollarTop := swag.FormatInt32(qrDollarTop)
		if qDollarTop != "" {

			if err := r.SetQueryParam("$top", qDollarTop); err != nil {
				return err
			}
		}
	}

	if o.XAvalaraClient != nil {

		// header param X-Avalara-Client
		if err := r.SetHeaderParam("X-Avalara-Client", *o.XAvalaraClient); err != nil {
			return err
		}
	}

	if o.End != nil {

		// query param end
		var qrEnd strfmt.DateTime

		if o.End != nil {
			qrEnd = *o.End
		}
		qEnd := qrEnd.String()
		if qEnd != "" {

			if err := r.SetQueryParam("end", qEnd); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if o.Start != nil {

		// query param start
		var qrStart strfmt.DateTime

		if o.Start != nil {
			qrStart = *o.Start
		}
		qStart := qrStart.String()
		if qStart != "" {

			if err := r.SetQueryParam("start", qStart); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
