// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/TomerHeber/avatax-v2-go/models"
)

// SetAccountConfigurationReader is a Reader for the SetAccountConfiguration structure.
type SetAccountConfigurationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetAccountConfigurationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetAccountConfigurationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSetAccountConfigurationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSetAccountConfigurationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSetAccountConfigurationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSetAccountConfigurationOK creates a SetAccountConfigurationOK with default headers values
func NewSetAccountConfigurationOK() *SetAccountConfigurationOK {
	return &SetAccountConfigurationOK{}
}

/* SetAccountConfigurationOK describes a response with status code 200, with default header values.

Success
*/
type SetAccountConfigurationOK struct {
	Payload []*models.AccountConfigurationModel
}

func (o *SetAccountConfigurationOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/accounts/{id}/configuration][%d] setAccountConfigurationOK  %+v", 200, o.Payload)
}
func (o *SetAccountConfigurationOK) GetPayload() []*models.AccountConfigurationModel {
	return o.Payload
}

func (o *SetAccountConfigurationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetAccountConfigurationBadRequest creates a SetAccountConfigurationBadRequest with default headers values
func NewSetAccountConfigurationBadRequest() *SetAccountConfigurationBadRequest {
	return &SetAccountConfigurationBadRequest{}
}

/* SetAccountConfigurationBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type SetAccountConfigurationBadRequest struct {
}

func (o *SetAccountConfigurationBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/accounts/{id}/configuration][%d] setAccountConfigurationBadRequest ", 400)
}

func (o *SetAccountConfigurationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetAccountConfigurationUnauthorized creates a SetAccountConfigurationUnauthorized with default headers values
func NewSetAccountConfigurationUnauthorized() *SetAccountConfigurationUnauthorized {
	return &SetAccountConfigurationUnauthorized{}
}

/* SetAccountConfigurationUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type SetAccountConfigurationUnauthorized struct {
}

func (o *SetAccountConfigurationUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v2/accounts/{id}/configuration][%d] setAccountConfigurationUnauthorized ", 401)
}

func (o *SetAccountConfigurationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetAccountConfigurationNotFound creates a SetAccountConfigurationNotFound with default headers values
func NewSetAccountConfigurationNotFound() *SetAccountConfigurationNotFound {
	return &SetAccountConfigurationNotFound{}
}

/* SetAccountConfigurationNotFound describes a response with status code 404, with default header values.

Not Found
*/
type SetAccountConfigurationNotFound struct {
}

func (o *SetAccountConfigurationNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v2/accounts/{id}/configuration][%d] setAccountConfigurationNotFound ", 404)
}

func (o *SetAccountConfigurationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
