// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AddressValidationInfo TextCase info for input address
// Example: {"city":"Irvine","country":"US","line1":"2000 Main Street","postalCode":"92614","region":"CA","textCase":"Upper"}
//
// swagger:model AddressValidationInfo
type AddressValidationInfo struct {

	// City component of the address
	// Example: Irvine
	// Max Length: 50
	// Min Length: 0
	City *string `json:"city,omitempty"`

	// Name or ISO 3166 code identifying the country.
	//
	// This field supports many different country identifiers:
	//  * Two character ISO 3166 codes
	//  * Three character ISO 3166 codes
	//  * Fully spelled out names of the country in ISO supported languages
	//  * Common alternative spellings for many countries
	//
	// For a full list of all supported codes and names, please see the Definitions API `ListCountries`.
	// Example: US
	Country string `json:"country,omitempty"`

	// Geospatial latitude measurement, in Decimal Degrees floating point format.
	Latitude float64 `json:"latitude,omitempty"`

	// First line of the street address
	// Example: 2000 Main Street
	// Max Length: 50
	// Min Length: 0
	Line1 *string `json:"line1,omitempty"`

	// Second line of the street address
	// Max Length: 100
	// Min Length: 0
	Line2 *string `json:"line2,omitempty"`

	// Third line of the street address
	// Max Length: 100
	// Min Length: 0
	Line3 *string `json:"line3,omitempty"`

	// Geospatial longitude measurement, in Decimal Degrees floating point format.
	Longitude float64 `json:"longitude,omitempty"`

	// Postal Code / Zip Code component of the address.
	// Example: 92614
	// Max Length: 11
	// Min Length: 0
	PostalCode *string `json:"postalCode,omitempty"`

	// Name or ISO 3166 code identifying the region within the country.
	//
	// This field supports many different region identifiers:
	//  * Two and three character ISO 3166 region codes
	//  * Fully spelled out names of the region in ISO supported languages
	//  * Common alternative spellings for many regions
	//
	// For a full list of all supported codes and names, please see the Definitions API `ListRegions`.
	// Example: CA
	Region string `json:"region,omitempty"`

	// Specify the text case for the validated address result.  If not specified, will return uppercase.
	// Example: Upper
	// Enum: [Upper Mixed]
	TextCase string `json:"textCase,omitempty"`
}

// Validate validates this address validation info
func (m *AddressValidationInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLine1(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLine2(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLine3(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePostalCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTextCase(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AddressValidationInfo) validateCity(formats strfmt.Registry) error {
	if swag.IsZero(m.City) { // not required
		return nil
	}

	if err := validate.MinLength("city", "body", *m.City, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("city", "body", *m.City, 50); err != nil {
		return err
	}

	return nil
}

func (m *AddressValidationInfo) validateLine1(formats strfmt.Registry) error {
	if swag.IsZero(m.Line1) { // not required
		return nil
	}

	if err := validate.MinLength("line1", "body", *m.Line1, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("line1", "body", *m.Line1, 50); err != nil {
		return err
	}

	return nil
}

func (m *AddressValidationInfo) validateLine2(formats strfmt.Registry) error {
	if swag.IsZero(m.Line2) { // not required
		return nil
	}

	if err := validate.MinLength("line2", "body", *m.Line2, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("line2", "body", *m.Line2, 100); err != nil {
		return err
	}

	return nil
}

func (m *AddressValidationInfo) validateLine3(formats strfmt.Registry) error {
	if swag.IsZero(m.Line3) { // not required
		return nil
	}

	if err := validate.MinLength("line3", "body", *m.Line3, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("line3", "body", *m.Line3, 100); err != nil {
		return err
	}

	return nil
}

func (m *AddressValidationInfo) validatePostalCode(formats strfmt.Registry) error {
	if swag.IsZero(m.PostalCode) { // not required
		return nil
	}

	if err := validate.MinLength("postalCode", "body", *m.PostalCode, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("postalCode", "body", *m.PostalCode, 11); err != nil {
		return err
	}

	return nil
}

var addressValidationInfoTypeTextCasePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Upper","Mixed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		addressValidationInfoTypeTextCasePropEnum = append(addressValidationInfoTypeTextCasePropEnum, v)
	}
}

const (

	// AddressValidationInfoTextCaseUpper captures enum value "Upper"
	AddressValidationInfoTextCaseUpper string = "Upper"

	// AddressValidationInfoTextCaseMixed captures enum value "Mixed"
	AddressValidationInfoTextCaseMixed string = "Mixed"
)

// prop value enum
func (m *AddressValidationInfo) validateTextCaseEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, addressValidationInfoTypeTextCasePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *AddressValidationInfo) validateTextCase(formats strfmt.Registry) error {
	if swag.IsZero(m.TextCase) { // not required
		return nil
	}

	// value enum
	if err := m.validateTextCaseEnum("textCase", "body", m.TextCase); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this address validation info based on context it is used
func (m *AddressValidationInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddressValidationInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddressValidationInfo) UnmarshalBinary(b []byte) error {
	var res AddressValidationInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
