// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AdvancedRuleExecutionOrderModel Model for updating rule execution order
// Example: {"ruleExecutionIds":["820e1e13dfea49cd835064fe1ddd6d1c","5312f524670f4e68bc49deab19a7921e"]}
//
// swagger:model AdvancedRuleExecutionOrderModel
type AdvancedRuleExecutionOrderModel struct {

	// The rule execution Ids in the desired order
	// Example: ["820e1e13dfea49cd835064fe1ddd6d1c","5312f524670f4e68bc49deab19a7921e"]
	// Required: true
	RuleExecutionIds []string `json:"ruleExecutionIds"`
}

// Validate validates this advanced rule execution order model
func (m *AdvancedRuleExecutionOrderModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRuleExecutionIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AdvancedRuleExecutionOrderModel) validateRuleExecutionIds(formats strfmt.Registry) error {

	if err := validate.Required("ruleExecutionIds", "body", m.RuleExecutionIds); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this advanced rule execution order model based on context it is used
func (m *AdvancedRuleExecutionOrderModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AdvancedRuleExecutionOrderModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AdvancedRuleExecutionOrderModel) UnmarshalBinary(b []byte) error {
	var res AdvancedRuleExecutionOrderModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
