// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CommitTransactionModel Commit this transaction as permanent so that it can be reported on a tax filing.
// Example: {"commit":true}
//
// swagger:model CommitTransactionModel
type CommitTransactionModel struct {

	// Set this value to be `true` to commit this transaction.
	//
	// Committing a transaction allows it to be reported on a tax filing.  Uncommitted transactions will not be reported.
	// Example: true
	// Required: true
	Commit *bool `json:"commit"`
}

// Validate validates this commit transaction model
func (m *CommitTransactionModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCommit(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CommitTransactionModel) validateCommit(formats strfmt.Registry) error {

	if err := validate.Required("commit", "body", m.Commit); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this commit transaction model based on context it is used
func (m *CommitTransactionModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CommitTransactionModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CommitTransactionModel) UnmarshalBinary(b []byte) error {
	var res CommitTransactionModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
