// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeleteErrorTransactionResponseModel Response model of a single error transaction delete
// Example: {"documentCode":"91cba92f-d649-409f-9d22-dcf0ee550fde","documentType":"SalesOrder","result":"Success"}
//
// swagger:model DeleteErrorTransactionResponseModel
type DeleteErrorTransactionResponseModel struct {

	// The internal reference code (used by the client application) of the error transaction
	// Example: 91cba92f-d649-409f-9d22-dcf0ee550fde
	// Required: true
	// Max Length: 50
	// Min Length: 0
	DocumentCode *string `json:"documentCode"`

	// Type of transaction of the error transaction
	// Example: SalesOrder
	// Required: true
	// Enum: [SalesOrder SalesInvoice PurchaseOrder PurchaseInvoice ReturnOrder ReturnInvoice InventoryTransferOrder InventoryTransferInvoice ReverseChargeOrder ReverseChargeInvoice CustomsInvoice CustomsOrder Any]
	DocumentType *string `json:"documentType"`

	// Result of the deletion
	// Example: Success
	// Enum: [Success Failure]
	Result string `json:"result,omitempty"`
}

// Validate validates this delete error transaction response model
func (m *DeleteErrorTransactionResponseModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDocumentCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDocumentType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeleteErrorTransactionResponseModel) validateDocumentCode(formats strfmt.Registry) error {

	if err := validate.Required("documentCode", "body", m.DocumentCode); err != nil {
		return err
	}

	if err := validate.MinLength("documentCode", "body", *m.DocumentCode, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("documentCode", "body", *m.DocumentCode, 50); err != nil {
		return err
	}

	return nil
}

var deleteErrorTransactionResponseModelTypeDocumentTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["SalesOrder","SalesInvoice","PurchaseOrder","PurchaseInvoice","ReturnOrder","ReturnInvoice","InventoryTransferOrder","InventoryTransferInvoice","ReverseChargeOrder","ReverseChargeInvoice","CustomsInvoice","CustomsOrder","Any"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		deleteErrorTransactionResponseModelTypeDocumentTypePropEnum = append(deleteErrorTransactionResponseModelTypeDocumentTypePropEnum, v)
	}
}

const (

	// DeleteErrorTransactionResponseModelDocumentTypeSalesOrder captures enum value "SalesOrder"
	DeleteErrorTransactionResponseModelDocumentTypeSalesOrder string = "SalesOrder"

	// DeleteErrorTransactionResponseModelDocumentTypeSalesInvoice captures enum value "SalesInvoice"
	DeleteErrorTransactionResponseModelDocumentTypeSalesInvoice string = "SalesInvoice"

	// DeleteErrorTransactionResponseModelDocumentTypePurchaseOrder captures enum value "PurchaseOrder"
	DeleteErrorTransactionResponseModelDocumentTypePurchaseOrder string = "PurchaseOrder"

	// DeleteErrorTransactionResponseModelDocumentTypePurchaseInvoice captures enum value "PurchaseInvoice"
	DeleteErrorTransactionResponseModelDocumentTypePurchaseInvoice string = "PurchaseInvoice"

	// DeleteErrorTransactionResponseModelDocumentTypeReturnOrder captures enum value "ReturnOrder"
	DeleteErrorTransactionResponseModelDocumentTypeReturnOrder string = "ReturnOrder"

	// DeleteErrorTransactionResponseModelDocumentTypeReturnInvoice captures enum value "ReturnInvoice"
	DeleteErrorTransactionResponseModelDocumentTypeReturnInvoice string = "ReturnInvoice"

	// DeleteErrorTransactionResponseModelDocumentTypeInventoryTransferOrder captures enum value "InventoryTransferOrder"
	DeleteErrorTransactionResponseModelDocumentTypeInventoryTransferOrder string = "InventoryTransferOrder"

	// DeleteErrorTransactionResponseModelDocumentTypeInventoryTransferInvoice captures enum value "InventoryTransferInvoice"
	DeleteErrorTransactionResponseModelDocumentTypeInventoryTransferInvoice string = "InventoryTransferInvoice"

	// DeleteErrorTransactionResponseModelDocumentTypeReverseChargeOrder captures enum value "ReverseChargeOrder"
	DeleteErrorTransactionResponseModelDocumentTypeReverseChargeOrder string = "ReverseChargeOrder"

	// DeleteErrorTransactionResponseModelDocumentTypeReverseChargeInvoice captures enum value "ReverseChargeInvoice"
	DeleteErrorTransactionResponseModelDocumentTypeReverseChargeInvoice string = "ReverseChargeInvoice"

	// DeleteErrorTransactionResponseModelDocumentTypeCustomsInvoice captures enum value "CustomsInvoice"
	DeleteErrorTransactionResponseModelDocumentTypeCustomsInvoice string = "CustomsInvoice"

	// DeleteErrorTransactionResponseModelDocumentTypeCustomsOrder captures enum value "CustomsOrder"
	DeleteErrorTransactionResponseModelDocumentTypeCustomsOrder string = "CustomsOrder"

	// DeleteErrorTransactionResponseModelDocumentTypeAny captures enum value "Any"
	DeleteErrorTransactionResponseModelDocumentTypeAny string = "Any"
)

// prop value enum
func (m *DeleteErrorTransactionResponseModel) validateDocumentTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, deleteErrorTransactionResponseModelTypeDocumentTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DeleteErrorTransactionResponseModel) validateDocumentType(formats strfmt.Registry) error {

	if err := validate.Required("documentType", "body", m.DocumentType); err != nil {
		return err
	}

	// value enum
	if err := m.validateDocumentTypeEnum("documentType", "body", *m.DocumentType); err != nil {
		return err
	}

	return nil
}

var deleteErrorTransactionResponseModelTypeResultPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Success","Failure"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		deleteErrorTransactionResponseModelTypeResultPropEnum = append(deleteErrorTransactionResponseModelTypeResultPropEnum, v)
	}
}

const (

	// DeleteErrorTransactionResponseModelResultSuccess captures enum value "Success"
	DeleteErrorTransactionResponseModelResultSuccess string = "Success"

	// DeleteErrorTransactionResponseModelResultFailure captures enum value "Failure"
	DeleteErrorTransactionResponseModelResultFailure string = "Failure"
)

// prop value enum
func (m *DeleteErrorTransactionResponseModel) validateResultEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, deleteErrorTransactionResponseModelTypeResultPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DeleteErrorTransactionResponseModel) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(m.Result) { // not required
		return nil
	}

	// value enum
	if err := m.validateResultEnum("result", "body", m.Result); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete error transaction response model based on context it is used
func (m *DeleteErrorTransactionResponseModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteErrorTransactionResponseModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteErrorTransactionResponseModel) UnmarshalBinary(b []byte) error {
	var res DeleteErrorTransactionResponseModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
