// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FilingReturnModel Filing Returns Model
// Example: {"accrualType":0,"adjustments":[{"accountType":"AccountsReceivableAccountsPayable","amount":100,"id":15634,"isCalculated":false,"period":"CurrentPeriod","type":"Discount"}],"augmentations":[{"fieldAmount":10,"fieldName":"Credit from the State","id":103230}],"carryOverConsumerUseTaxAmount":0,"carryOverNonTaxableAmount":0,"carryOverSalesAmount":0,"carryOverTaxAmount":0,"collectAmount":1,"consumerUseNonTaxableAccrualAmount":0,"consumerUseNonTaxableAmount":0,"consumerUseTaxAccrualAmount":0,"consumerUseTaxAmount":0,"consumerUseTaxDueAmount":0,"consumerUseTaxableAccrualAmount":0,"consumerUseTaxableAmount":0,"description":"Sales Tax Return","excludedNonTaxableAmount":0,"excludedSalesAmount":0,"excludedTaxAmount":0,"filingCalendarId":513256,"filingFrequency":"Monthly","filingRegionId":0,"filingType":"ElectronicReturn","formCode":"AL2100","formName":"AL 2100","id":5233103,"nonTaxableAccrualAmount":0,"nonTaxableAmount":0,"nonTaxableDueAmount":0,"remitAmount":0,"salesAccrualAmount":0,"salesAmount":0,"salesTaxAccrualAmount":0,"sellersUseTaxAccrualAmount":0,"status":"PendingApproval","taxAccrualAmount":0,"taxAmount":0,"taxDueAmount":0,"taxableAccrualAmount":0,"taxableAmount":0,"totalAdjustments":0,"totalAugmentations":0,"totalPayments":0}
//
// swagger:model FilingReturnModel
type FilingReturnModel struct {

	// Accrual type of the return
	// Example: Filing
	// Enum: [Filing Accrual]
	AccrualType string `json:"accrualType,omitempty"`

	// The Adjustments for this return.
	// Example: [{"accountType":"AccountsReceivableAccountsPayable","amount":100,"id":15634,"isCalculated":false,"period":"CurrentPeriod","type":"Discount"}]
	Adjustments []*FilingAdjustmentModel `json:"adjustments"`

	// The applied carry over credit documents
	// Example: {"totalExempt":0,"totalSales":0,"totalTax":0,"totalTaxable":0}
	AppliedCarryOverCredits *FilingReturnCreditModel `json:"appliedCarryOverCredits,omitempty"`

	// The attachments for this return.
	Attachments []*FilingAttachmentModel `json:"attachments"`

	// The Augmentations for this return.
	// Example: [{"fieldAmount":10,"fieldName":"Credit from the State","id":103230}]
	Augmentations []*FilingAugmentationModel `json:"augmentations"`

	// The amount of carry over consumer use tax applied to the liability calculation
	// Example: 0
	CarryOverConsumerUseTaxAmount float64 `json:"carryOverConsumerUseTaxAmount,omitempty"`

	// The amount of carry over non taxable sales applied to the liability calculation
	// Example: 0
	CarryOverNonTaxableAmount float64 `json:"carryOverNonTaxableAmount,omitempty"`

	// The amount of carry over sales applied to the liability calculation
	// Example: 0
	CarryOverSalesAmount float64 `json:"carryOverSalesAmount,omitempty"`

	// The amount of carry over sales tax applied to the liability calculation
	// Example: 0
	CarryOverTaxAmount float64 `json:"carryOverTaxAmount,omitempty"`

	// The amount collected by avalara for this return
	// Example: 1
	CollectAmount float64 `json:"collectAmount,omitempty"`

	// The total amount of consumer use non taxable sales accrued in the current active period
	// Example: 0
	ConsumerUseNonTaxableAccrualAmount float64 `json:"consumerUseNonTaxableAccrualAmount,omitempty"`

	// Consumer use non-taxable amount.
	// Example: 0
	ConsumerUseNonTaxableAmount float64 `json:"consumerUseNonTaxableAmount,omitempty"`

	// The total amount of consumer use tax accrued in the current active period
	// Example: 0
	ConsumerUseTaxAccrualAmount float64 `json:"consumerUseTaxAccrualAmount,omitempty"`

	// Consumer use tax liability during the period.
	// Example: 0
	ConsumerUseTaxAmount float64 `json:"consumerUseTaxAmount,omitempty"`

	// Consumer use tax liability accrued during the period.
	// Example: 0
	ConsumerUseTaxDueAmount float64 `json:"consumerUseTaxDueAmount,omitempty"`

	// The total amount of consumer use taxable sales accrued in the current active period
	// Example: 0
	ConsumerUseTaxableAccrualAmount float64 `json:"consumerUseTaxableAccrualAmount,omitempty"`

	// Consumer use taxable amount.
	// Example: 0
	ConsumerUseTaxableAmount float64 `json:"consumerUseTaxableAmount,omitempty"`

	// The date when this record was created.
	// Read Only: true
	// Format: date-time
	CreatedDate strfmt.DateTime `json:"createdDate,omitempty"`

	// The User ID of the user who created this record.
	// Read Only: true
	CreatedUserID int32 `json:"createdUserId,omitempty"`

	// A description for the return.
	// Example: Sales Tax Return
	Description string `json:"description,omitempty"`

	// The end date of this return
	// Format: date-time
	EndPeriod strfmt.DateTime `json:"endPeriod,omitempty"`

	// The excluded carry over credit documents
	// Example: {"totalExempt":0,"totalSales":0,"totalTax":0,"totalTaxable":0}
	ExcludedCarryOverCredits *FilingReturnCreditModel `json:"excludedCarryOverCredits,omitempty"`

	// The amount of non-taxable sales excluded from the liability calculation
	// Example: 0
	ExcludedNonTaxableAmount float64 `json:"excludedNonTaxableAmount,omitempty"`

	// The amount of sales excluded from the liability calculation
	// Example: 0
	ExcludedSalesAmount float64 `json:"excludedSalesAmount,omitempty"`

	// The amount of tax excluded from the liability calculation
	// Example: 0
	ExcludedTaxAmount float64 `json:"excludedTaxAmount,omitempty"`

	// The date the return was filed by Avalara.
	// Format: date-time
	FiledDate strfmt.DateTime `json:"filedDate,omitempty"`

	// The unique ID number of the filing calendar associated with this return.
	// Example: 513256
	FilingCalendarID int64 `json:"filingCalendarId,omitempty"`

	// The filing frequency of the return.
	// Example: Monthly
	// Enum: [Monthly Quarterly SemiAnnually Annually Bimonthly Occasional InverseQuarterly Weekly]
	FilingFrequency string `json:"filingFrequency,omitempty"`

	// The region id that this return belongs too
	// Example: 0
	FilingRegionID int64 `json:"filingRegionId,omitempty"`

	// The filing type of the return.
	// Example: PaperReturn
	// Enum: [PaperReturn ElectronicReturn SER EFTPaper PhonePaper SignatureReady EfileCheck]
	FilingType string `json:"filingType,omitempty"`

	// The unique code of the form.
	// Example: AL2100
	FormCode string `json:"formCode,omitempty"`

	// The name of the form.
	// Example: AL 2100
	FormName string `json:"formName,omitempty"`

	// The unique ID number of this filing return.
	// Example: 5233103
	ID int64 `json:"id,omitempty"`

	// The date/time when this record was last modified.
	// Read Only: true
	// Format: date-time
	ModifiedDate strfmt.DateTime `json:"modifiedDate,omitempty"`

	// The month of the filing period for this tax filing.
	// The filing period represents the year and month of the last day of taxes being reported on this filing.
	// For example, an annual tax filing for Jan-Dec 2015 would have a filing period of Dec 2015.
	Month int32 `json:"month,omitempty"`

	// The total amount of nontaxable sales accrued in the current active period
	// Example: 0
	NonTaxableAccrualAmount float64 `json:"nonTaxableAccrualAmount,omitempty"`

	// The non-taxable amount.
	// Example: 0
	NonTaxableAmount float64 `json:"nonTaxableAmount,omitempty"`

	// The non-taxable due amount.
	// Example: 0
	NonTaxableDueAmount float64 `json:"nonTaxableDueAmount,omitempty"`

	// The payments for this return.
	Payments []*FilingPaymentModel `json:"payments"`

	// The remittance amount of the return.
	// Example: 0
	RemitAmount float64 `json:"remitAmount,omitempty"`

	// The resourceFileId of the return.  Will be null if not available.
	ResourceFileID int64 `json:"resourceFileId,omitempty"`

	// The total amount of sales accrued in the current active period
	// Example: 0
	SalesAccrualAmount float64 `json:"salesAccrualAmount,omitempty"`

	// The sales amount.
	// Example: 0
	SalesAmount float64 `json:"salesAmount,omitempty"`

	// The total amount of sales tax accrued in the current active period
	// Example: 0
	SalesTaxAccrualAmount float64 `json:"salesTaxAccrualAmount,omitempty"`

	// The total amount of sellers use tax accrued in the current active period
	// Example: 0
	SellersUseTaxAccrualAmount float64 `json:"sellersUseTaxAccrualAmount,omitempty"`

	// The start date of this return
	// Format: date-time
	StartPeriod strfmt.DateTime `json:"startPeriod,omitempty"`

	// The current status of the filing return.
	// Example: PendingApproval
	// Enum: [PendingApproval Dirty ApprovedToFile PendingFiling PendingFilingOnBehalf Filed FiledOnBehalf ReturnAccepted ReturnAcceptedOnBehalf PaymentRemitted Voided PendingReturn PendingReturnOnBehalf DoNotFile ReturnRejected ReturnRejectedOnBehalf ApprovedToFileOnBehalf]
	Status string `json:"status,omitempty"`

	// The total amount of total tax accrued in the current active period
	// Example: 0
	TaxAccrualAmount float64 `json:"taxAccrualAmount,omitempty"`

	// The tax amount.
	// Example: 0
	TaxAmount float64 `json:"taxAmount,omitempty"`

	// Tax Authority ID of this return
	TaxAuthorityID int32 `json:"taxAuthorityId,omitempty"`

	// The tax due amount.
	// Example: 0
	TaxDueAmount float64 `json:"taxDueAmount,omitempty"`

	// The total amount of taxable sales accrued in the current active period
	// Example: 0
	TaxableAccrualAmount float64 `json:"taxableAccrualAmount,omitempty"`

	// The taxable amount.
	// Example: 0
	TaxableAmount float64 `json:"taxableAmount,omitempty"`

	// Total amount of adjustments on this return
	// Example: 0
	TotalAdjustments float64 `json:"totalAdjustments,omitempty"`

	// Total amount of augmentations on this return
	// Example: 0
	TotalAugmentations float64 `json:"totalAugmentations,omitempty"`

	// Total amount of payments on this return
	// Example: 0
	TotalPayments float64 `json:"totalPayments,omitempty"`

	// The FilingTaskType for this return.
	Type string `json:"type,omitempty"`

	// The year of the filing period for this tax filing.
	// The filing period represents the year and month of the last day of taxes being reported on this filing.
	// For example, an annual tax filing for Jan-Dec 2015 would have a filing period of Dec 2015.
	Year int32 `json:"year,omitempty"`
}

// Validate validates this filing return model
func (m *FilingReturnModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccrualType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAdjustments(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAppliedCarryOverCredits(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAttachments(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAugmentations(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEndPeriod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExcludedCarryOverCredits(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFiledDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFilingFrequency(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFilingType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateModifiedDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePayments(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStartPeriod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var filingReturnModelTypeAccrualTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Filing","Accrual"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		filingReturnModelTypeAccrualTypePropEnum = append(filingReturnModelTypeAccrualTypePropEnum, v)
	}
}

const (

	// FilingReturnModelAccrualTypeFiling captures enum value "Filing"
	FilingReturnModelAccrualTypeFiling string = "Filing"

	// FilingReturnModelAccrualTypeAccrual captures enum value "Accrual"
	FilingReturnModelAccrualTypeAccrual string = "Accrual"
)

// prop value enum
func (m *FilingReturnModel) validateAccrualTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, filingReturnModelTypeAccrualTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *FilingReturnModel) validateAccrualType(formats strfmt.Registry) error {
	if swag.IsZero(m.AccrualType) { // not required
		return nil
	}

	// value enum
	if err := m.validateAccrualTypeEnum("accrualType", "body", m.AccrualType); err != nil {
		return err
	}

	return nil
}

func (m *FilingReturnModel) validateAdjustments(formats strfmt.Registry) error {
	if swag.IsZero(m.Adjustments) { // not required
		return nil
	}

	for i := 0; i < len(m.Adjustments); i++ {
		if swag.IsZero(m.Adjustments[i]) { // not required
			continue
		}

		if m.Adjustments[i] != nil {
			if err := m.Adjustments[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("adjustments" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("adjustments" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *FilingReturnModel) validateAppliedCarryOverCredits(formats strfmt.Registry) error {
	if swag.IsZero(m.AppliedCarryOverCredits) { // not required
		return nil
	}

	if m.AppliedCarryOverCredits != nil {
		if err := m.AppliedCarryOverCredits.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("appliedCarryOverCredits")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("appliedCarryOverCredits")
			}
			return err
		}
	}

	return nil
}

func (m *FilingReturnModel) validateAttachments(formats strfmt.Registry) error {
	if swag.IsZero(m.Attachments) { // not required
		return nil
	}

	for i := 0; i < len(m.Attachments); i++ {
		if swag.IsZero(m.Attachments[i]) { // not required
			continue
		}

		if m.Attachments[i] != nil {
			if err := m.Attachments[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("attachments" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("attachments" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *FilingReturnModel) validateAugmentations(formats strfmt.Registry) error {
	if swag.IsZero(m.Augmentations) { // not required
		return nil
	}

	for i := 0; i < len(m.Augmentations); i++ {
		if swag.IsZero(m.Augmentations[i]) { // not required
			continue
		}

		if m.Augmentations[i] != nil {
			if err := m.Augmentations[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("augmentations" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("augmentations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *FilingReturnModel) validateCreatedDate(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedDate) { // not required
		return nil
	}

	if err := validate.FormatOf("createdDate", "body", "date-time", m.CreatedDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *FilingReturnModel) validateEndPeriod(formats strfmt.Registry) error {
	if swag.IsZero(m.EndPeriod) { // not required
		return nil
	}

	if err := validate.FormatOf("endPeriod", "body", "date-time", m.EndPeriod.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *FilingReturnModel) validateExcludedCarryOverCredits(formats strfmt.Registry) error {
	if swag.IsZero(m.ExcludedCarryOverCredits) { // not required
		return nil
	}

	if m.ExcludedCarryOverCredits != nil {
		if err := m.ExcludedCarryOverCredits.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("excludedCarryOverCredits")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("excludedCarryOverCredits")
			}
			return err
		}
	}

	return nil
}

func (m *FilingReturnModel) validateFiledDate(formats strfmt.Registry) error {
	if swag.IsZero(m.FiledDate) { // not required
		return nil
	}

	if err := validate.FormatOf("filedDate", "body", "date-time", m.FiledDate.String(), formats); err != nil {
		return err
	}

	return nil
}

var filingReturnModelTypeFilingFrequencyPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Monthly","Quarterly","SemiAnnually","Annually","Bimonthly","Occasional","InverseQuarterly","Weekly"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		filingReturnModelTypeFilingFrequencyPropEnum = append(filingReturnModelTypeFilingFrequencyPropEnum, v)
	}
}

const (

	// FilingReturnModelFilingFrequencyMonthly captures enum value "Monthly"
	FilingReturnModelFilingFrequencyMonthly string = "Monthly"

	// FilingReturnModelFilingFrequencyQuarterly captures enum value "Quarterly"
	FilingReturnModelFilingFrequencyQuarterly string = "Quarterly"

	// FilingReturnModelFilingFrequencySemiAnnually captures enum value "SemiAnnually"
	FilingReturnModelFilingFrequencySemiAnnually string = "SemiAnnually"

	// FilingReturnModelFilingFrequencyAnnually captures enum value "Annually"
	FilingReturnModelFilingFrequencyAnnually string = "Annually"

	// FilingReturnModelFilingFrequencyBimonthly captures enum value "Bimonthly"
	FilingReturnModelFilingFrequencyBimonthly string = "Bimonthly"

	// FilingReturnModelFilingFrequencyOccasional captures enum value "Occasional"
	FilingReturnModelFilingFrequencyOccasional string = "Occasional"

	// FilingReturnModelFilingFrequencyInverseQuarterly captures enum value "InverseQuarterly"
	FilingReturnModelFilingFrequencyInverseQuarterly string = "InverseQuarterly"

	// FilingReturnModelFilingFrequencyWeekly captures enum value "Weekly"
	FilingReturnModelFilingFrequencyWeekly string = "Weekly"
)

// prop value enum
func (m *FilingReturnModel) validateFilingFrequencyEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, filingReturnModelTypeFilingFrequencyPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *FilingReturnModel) validateFilingFrequency(formats strfmt.Registry) error {
	if swag.IsZero(m.FilingFrequency) { // not required
		return nil
	}

	// value enum
	if err := m.validateFilingFrequencyEnum("filingFrequency", "body", m.FilingFrequency); err != nil {
		return err
	}

	return nil
}

var filingReturnModelTypeFilingTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["PaperReturn","ElectronicReturn","SER","EFTPaper","PhonePaper","SignatureReady","EfileCheck"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		filingReturnModelTypeFilingTypePropEnum = append(filingReturnModelTypeFilingTypePropEnum, v)
	}
}

const (

	// FilingReturnModelFilingTypePaperReturn captures enum value "PaperReturn"
	FilingReturnModelFilingTypePaperReturn string = "PaperReturn"

	// FilingReturnModelFilingTypeElectronicReturn captures enum value "ElectronicReturn"
	FilingReturnModelFilingTypeElectronicReturn string = "ElectronicReturn"

	// FilingReturnModelFilingTypeSER captures enum value "SER"
	FilingReturnModelFilingTypeSER string = "SER"

	// FilingReturnModelFilingTypeEFTPaper captures enum value "EFTPaper"
	FilingReturnModelFilingTypeEFTPaper string = "EFTPaper"

	// FilingReturnModelFilingTypePhonePaper captures enum value "PhonePaper"
	FilingReturnModelFilingTypePhonePaper string = "PhonePaper"

	// FilingReturnModelFilingTypeSignatureReady captures enum value "SignatureReady"
	FilingReturnModelFilingTypeSignatureReady string = "SignatureReady"

	// FilingReturnModelFilingTypeEfileCheck captures enum value "EfileCheck"
	FilingReturnModelFilingTypeEfileCheck string = "EfileCheck"
)

// prop value enum
func (m *FilingReturnModel) validateFilingTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, filingReturnModelTypeFilingTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *FilingReturnModel) validateFilingType(formats strfmt.Registry) error {
	if swag.IsZero(m.FilingType) { // not required
		return nil
	}

	// value enum
	if err := m.validateFilingTypeEnum("filingType", "body", m.FilingType); err != nil {
		return err
	}

	return nil
}

func (m *FilingReturnModel) validateModifiedDate(formats strfmt.Registry) error {
	if swag.IsZero(m.ModifiedDate) { // not required
		return nil
	}

	if err := validate.FormatOf("modifiedDate", "body", "date-time", m.ModifiedDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *FilingReturnModel) validatePayments(formats strfmt.Registry) error {
	if swag.IsZero(m.Payments) { // not required
		return nil
	}

	for i := 0; i < len(m.Payments); i++ {
		if swag.IsZero(m.Payments[i]) { // not required
			continue
		}

		if m.Payments[i] != nil {
			if err := m.Payments[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("payments" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("payments" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *FilingReturnModel) validateStartPeriod(formats strfmt.Registry) error {
	if swag.IsZero(m.StartPeriod) { // not required
		return nil
	}

	if err := validate.FormatOf("startPeriod", "body", "date-time", m.StartPeriod.String(), formats); err != nil {
		return err
	}

	return nil
}

var filingReturnModelTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["PendingApproval","Dirty","ApprovedToFile","PendingFiling","PendingFilingOnBehalf","Filed","FiledOnBehalf","ReturnAccepted","ReturnAcceptedOnBehalf","PaymentRemitted","Voided","PendingReturn","PendingReturnOnBehalf","DoNotFile","ReturnRejected","ReturnRejectedOnBehalf","ApprovedToFileOnBehalf"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		filingReturnModelTypeStatusPropEnum = append(filingReturnModelTypeStatusPropEnum, v)
	}
}

const (

	// FilingReturnModelStatusPendingApproval captures enum value "PendingApproval"
	FilingReturnModelStatusPendingApproval string = "PendingApproval"

	// FilingReturnModelStatusDirty captures enum value "Dirty"
	FilingReturnModelStatusDirty string = "Dirty"

	// FilingReturnModelStatusApprovedToFile captures enum value "ApprovedToFile"
	FilingReturnModelStatusApprovedToFile string = "ApprovedToFile"

	// FilingReturnModelStatusPendingFiling captures enum value "PendingFiling"
	FilingReturnModelStatusPendingFiling string = "PendingFiling"

	// FilingReturnModelStatusPendingFilingOnBehalf captures enum value "PendingFilingOnBehalf"
	FilingReturnModelStatusPendingFilingOnBehalf string = "PendingFilingOnBehalf"

	// FilingReturnModelStatusFiled captures enum value "Filed"
	FilingReturnModelStatusFiled string = "Filed"

	// FilingReturnModelStatusFiledOnBehalf captures enum value "FiledOnBehalf"
	FilingReturnModelStatusFiledOnBehalf string = "FiledOnBehalf"

	// FilingReturnModelStatusReturnAccepted captures enum value "ReturnAccepted"
	FilingReturnModelStatusReturnAccepted string = "ReturnAccepted"

	// FilingReturnModelStatusReturnAcceptedOnBehalf captures enum value "ReturnAcceptedOnBehalf"
	FilingReturnModelStatusReturnAcceptedOnBehalf string = "ReturnAcceptedOnBehalf"

	// FilingReturnModelStatusPaymentRemitted captures enum value "PaymentRemitted"
	FilingReturnModelStatusPaymentRemitted string = "PaymentRemitted"

	// FilingReturnModelStatusVoided captures enum value "Voided"
	FilingReturnModelStatusVoided string = "Voided"

	// FilingReturnModelStatusPendingReturn captures enum value "PendingReturn"
	FilingReturnModelStatusPendingReturn string = "PendingReturn"

	// FilingReturnModelStatusPendingReturnOnBehalf captures enum value "PendingReturnOnBehalf"
	FilingReturnModelStatusPendingReturnOnBehalf string = "PendingReturnOnBehalf"

	// FilingReturnModelStatusDoNotFile captures enum value "DoNotFile"
	FilingReturnModelStatusDoNotFile string = "DoNotFile"

	// FilingReturnModelStatusReturnRejected captures enum value "ReturnRejected"
	FilingReturnModelStatusReturnRejected string = "ReturnRejected"

	// FilingReturnModelStatusReturnRejectedOnBehalf captures enum value "ReturnRejectedOnBehalf"
	FilingReturnModelStatusReturnRejectedOnBehalf string = "ReturnRejectedOnBehalf"

	// FilingReturnModelStatusApprovedToFileOnBehalf captures enum value "ApprovedToFileOnBehalf"
	FilingReturnModelStatusApprovedToFileOnBehalf string = "ApprovedToFileOnBehalf"
)

// prop value enum
func (m *FilingReturnModel) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, filingReturnModelTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *FilingReturnModel) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this filing return model based on the context it is used
func (m *FilingReturnModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAdjustments(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAppliedCarryOverCredits(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAttachments(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAugmentations(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreatedDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreatedUserID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExcludedCarryOverCredits(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateModifiedDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePayments(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FilingReturnModel) contextValidateAdjustments(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Adjustments); i++ {

		if m.Adjustments[i] != nil {
			if err := m.Adjustments[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("adjustments" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("adjustments" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *FilingReturnModel) contextValidateAppliedCarryOverCredits(ctx context.Context, formats strfmt.Registry) error {

	if m.AppliedCarryOverCredits != nil {
		if err := m.AppliedCarryOverCredits.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("appliedCarryOverCredits")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("appliedCarryOverCredits")
			}
			return err
		}
	}

	return nil
}

func (m *FilingReturnModel) contextValidateAttachments(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Attachments); i++ {

		if m.Attachments[i] != nil {
			if err := m.Attachments[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("attachments" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("attachments" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *FilingReturnModel) contextValidateAugmentations(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Augmentations); i++ {

		if m.Augmentations[i] != nil {
			if err := m.Augmentations[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("augmentations" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("augmentations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *FilingReturnModel) contextValidateCreatedDate(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "createdDate", "body", strfmt.DateTime(m.CreatedDate)); err != nil {
		return err
	}

	return nil
}

func (m *FilingReturnModel) contextValidateCreatedUserID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "createdUserId", "body", int32(m.CreatedUserID)); err != nil {
		return err
	}

	return nil
}

func (m *FilingReturnModel) contextValidateExcludedCarryOverCredits(ctx context.Context, formats strfmt.Registry) error {

	if m.ExcludedCarryOverCredits != nil {
		if err := m.ExcludedCarryOverCredits.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("excludedCarryOverCredits")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("excludedCarryOverCredits")
			}
			return err
		}
	}

	return nil
}

func (m *FilingReturnModel) contextValidateModifiedDate(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "modifiedDate", "body", strfmt.DateTime(m.ModifiedDate)); err != nil {
		return err
	}

	return nil
}

func (m *FilingReturnModel) contextValidatePayments(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Payments); i++ {

		if m.Payments[i] != nil {
			if err := m.Payments[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("payments" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("payments" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *FilingReturnModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FilingReturnModel) UnmarshalBinary(b []byte) error {
	var res FilingReturnModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
