// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LocationSettingModel Represents the answer to one local jurisdiction question for a location.
// Example: {"questionId":17,"value":"abcdefghij"}
//
// swagger:model LocationSettingModel
type LocationSettingModel struct {

	// The unique ID number of the location question answered.
	// Example: 17
	QuestionID int32 `json:"questionId,omitempty"`

	// The name of the question
	QuestionName string `json:"questionName,omitempty"`

	// The answer the user provided.
	// Example: abcdefghij
	// Max Length: 50
	// Min Length: 0
	Value *string `json:"value,omitempty"`
}

// Validate validates this location setting model
func (m *LocationSettingModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LocationSettingModel) validateValue(formats strfmt.Registry) error {
	if swag.IsZero(m.Value) { // not required
		return nil
	}

	if err := validate.MinLength("value", "body", *m.Value, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("value", "body", *m.Value, 50); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this location setting model based on context it is used
func (m *LocationSettingModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LocationSettingModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LocationSettingModel) UnmarshalBinary(b []byte) error {
	var res LocationSettingModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
