// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PowerOfAttorneyCheckModel Response when checking if a company has a POA on file with Avalara
// Example: {"activePoa":true,"companyId":12345,"country":"US","region":"WI"}
//
// swagger:model PowerOfAttorneyCheckModel
type PowerOfAttorneyCheckModel struct {

	// Notes if there is an actice POA
	// Example: true
	ActivePoa bool `json:"activePoa,omitempty"`

	// POA download
	AvailablePoa *ResourceFileDownloadResult `json:"availablePoa,omitempty"`

	// companyId of the request
	// Example: 12345
	CompanyID int32 `json:"companyId,omitempty"`

	// Country POA is for
	// Example: US
	Country string `json:"country,omitempty"`

	// Effective Date of the POA
	// Format: date-time
	EffectiveDate strfmt.DateTime `json:"effectiveDate,omitempty"`

	// End Date of POA
	// Format: date-time
	ExpirationDate strfmt.DateTime `json:"expirationDate,omitempty"`

	// Region POA is for
	// Example: WI
	Region string `json:"region,omitempty"`
}

// Validate validates this power of attorney check model
func (m *PowerOfAttorneyCheckModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAvailablePoa(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEffectiveDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpirationDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PowerOfAttorneyCheckModel) validateAvailablePoa(formats strfmt.Registry) error {
	if swag.IsZero(m.AvailablePoa) { // not required
		return nil
	}

	if m.AvailablePoa != nil {
		if err := m.AvailablePoa.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("availablePoa")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("availablePoa")
			}
			return err
		}
	}

	return nil
}

func (m *PowerOfAttorneyCheckModel) validateEffectiveDate(formats strfmt.Registry) error {
	if swag.IsZero(m.EffectiveDate) { // not required
		return nil
	}

	if err := validate.FormatOf("effectiveDate", "body", "date-time", m.EffectiveDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *PowerOfAttorneyCheckModel) validateExpirationDate(formats strfmt.Registry) error {
	if swag.IsZero(m.ExpirationDate) { // not required
		return nil
	}

	if err := validate.FormatOf("expirationDate", "body", "date-time", m.ExpirationDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this power of attorney check model based on the context it is used
func (m *PowerOfAttorneyCheckModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAvailablePoa(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PowerOfAttorneyCheckModel) contextValidateAvailablePoa(ctx context.Context, formats strfmt.Registry) error {

	if m.AvailablePoa != nil {
		if err := m.AvailablePoa.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("availablePoa")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("availablePoa")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PowerOfAttorneyCheckModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PowerOfAttorneyCheckModel) UnmarshalBinary(b []byte) error {
	var res PowerOfAttorneyCheckModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
