// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RefundTransactionModel Refund a committed transaction
// Example: {"referenceCode":"Refund for a committed transaction","refundDate":"2021-12-25","refundTransactionCode":"0941711e-bd22-43ac-998d-85616b6fc9d9","refundType":"Full"}
//
// swagger:model RefundTransactionModel
type RefundTransactionModel struct {

	// A user-defined reference field containing information about this refund.
	// Example: Refund for a committed transaction
	ReferenceCode string `json:"referenceCode,omitempty"`

	// The date of the refund.  For customers using Avalara's Managed Returns Service, this date controls the month in which the refund
	// transaction will be reported on a tax filing.
	// Example: 2021-12-25T00:00:00+00:00
	// Required: true
	// Format: date
	RefundDate *strfmt.Date `json:"refundDate"`

	// If you chose a refund of type `Partial`, this indicates which lines from the original transaction are being refunded.
	RefundLines []string `json:"refundLines"`

	// The percentage for refund.
	//
	// This value only applies if you choose `refundType = Percentage` or `refundType = Partial`.
	RefundPercentage float64 `json:"refundPercentage,omitempty"`

	// The transaction code for the refund.  This code will be saved to the `ReturnInvoice` transaction, and does not need to match the code of the original sale.
	// Example: 0941711e-bd22-43ac-998d-85616b6fc9d9
	// Max Length: 50
	// Min Length: 0
	RefundTransactionCode *string `json:"refundTransactionCode,omitempty"`

	// Type of this refund.
	//
	// To submit a full refund, specify `Full`.
	//
	// To refund only specific lines from the transaction, specify `Partial` and indicate the lines you wish to apply in the `refundLines` field.
	//
	// To refund the tax that was paid in the previous transaction, specify `TaxOnly`.
	//
	// To issue a percentage-based discount, specify `Percentage`.
	// Example: Full
	// Enum: [Full Partial TaxOnly Percentage]
	RefundType string `json:"refundType,omitempty"`
}

// Validate validates this refund transaction model
func (m *RefundTransactionModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRefundDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRefundTransactionCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRefundType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RefundTransactionModel) validateRefundDate(formats strfmt.Registry) error {

	if err := validate.Required("refundDate", "body", m.RefundDate); err != nil {
		return err
	}

	if err := validate.FormatOf("refundDate", "body", "date", m.RefundDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *RefundTransactionModel) validateRefundTransactionCode(formats strfmt.Registry) error {
	if swag.IsZero(m.RefundTransactionCode) { // not required
		return nil
	}

	if err := validate.MinLength("refundTransactionCode", "body", *m.RefundTransactionCode, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("refundTransactionCode", "body", *m.RefundTransactionCode, 50); err != nil {
		return err
	}

	return nil
}

var refundTransactionModelTypeRefundTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Full","Partial","TaxOnly","Percentage"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		refundTransactionModelTypeRefundTypePropEnum = append(refundTransactionModelTypeRefundTypePropEnum, v)
	}
}

const (

	// RefundTransactionModelRefundTypeFull captures enum value "Full"
	RefundTransactionModelRefundTypeFull string = "Full"

	// RefundTransactionModelRefundTypePartial captures enum value "Partial"
	RefundTransactionModelRefundTypePartial string = "Partial"

	// RefundTransactionModelRefundTypeTaxOnly captures enum value "TaxOnly"
	RefundTransactionModelRefundTypeTaxOnly string = "TaxOnly"

	// RefundTransactionModelRefundTypePercentage captures enum value "Percentage"
	RefundTransactionModelRefundTypePercentage string = "Percentage"
)

// prop value enum
func (m *RefundTransactionModel) validateRefundTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, refundTransactionModelTypeRefundTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *RefundTransactionModel) validateRefundType(formats strfmt.Registry) error {
	if swag.IsZero(m.RefundType) { // not required
		return nil
	}

	// value enum
	if err := m.validateRefundTypeEnum("refundType", "body", m.RefundType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this refund transaction model based on context it is used
func (m *RefundTransactionModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RefundTransactionModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RefundTransactionModel) UnmarshalBinary(b []byte) error {
	var res RefundTransactionModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
