// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SettleTransactionModel Settle this transaction with your ledger by executing one or many actions against that transaction.
//
// You may use this endpoint to verify the transaction, change the transaction's code, and commit the transaction for reporting purposes.
// This endpoint may be used to execute any or all of these actions at once.
// Example: {"changeCode":{"newCode":"f5c5dde4-051a-4b95-a298-9c65cce417e4"},"commit":{"commit":true},"verify":{"verifyTotalAmount":100,"verifyTotalTax":6.25,"verifyTransactionDate":"2021-12-25T00:00:00+00:00"}}
//
// swagger:model SettleTransactionModel
type SettleTransactionModel struct {

	// To change the code for this transaction, you may provide information in this field.
	//
	// If you leave this field null, the transaction's code will not be changed.
	// Example: {"newCode":"f5c5dde4-051a-4b95-a298-9c65cce417e4"}
	ChangeCode *ChangeTransactionCodeModel `json:"changeCode,omitempty"`

	// To commit this transaction so that it can be reported on a tax filing, you may provide information in this field.
	//
	// If you leave this field null, the transaction's commit status will not be changed.
	//
	// If you use Avalara's Managed Returns Service, committing a transaction will allow that transaction to be filed.
	// Example: {"commit":true}
	Commit *CommitTransactionModel `json:"commit,omitempty"`

	// To verify this transaction, you may provide information in this field.
	//
	// If you leave this field null, the transaction will not be verified.
	// Example: {"verifyTotalAmount":100,"verifyTotalTax":6.25,"verifyTransactionDate":"2021-12-25T00:00:00+00:00"}
	Verify *VerifyTransactionModel `json:"verify,omitempty"`
}

// Validate validates this settle transaction model
func (m *SettleTransactionModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChangeCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCommit(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVerify(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SettleTransactionModel) validateChangeCode(formats strfmt.Registry) error {
	if swag.IsZero(m.ChangeCode) { // not required
		return nil
	}

	if m.ChangeCode != nil {
		if err := m.ChangeCode.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("changeCode")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("changeCode")
			}
			return err
		}
	}

	return nil
}

func (m *SettleTransactionModel) validateCommit(formats strfmt.Registry) error {
	if swag.IsZero(m.Commit) { // not required
		return nil
	}

	if m.Commit != nil {
		if err := m.Commit.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("commit")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("commit")
			}
			return err
		}
	}

	return nil
}

func (m *SettleTransactionModel) validateVerify(formats strfmt.Registry) error {
	if swag.IsZero(m.Verify) { // not required
		return nil
	}

	if m.Verify != nil {
		if err := m.Verify.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("verify")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("verify")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this settle transaction model based on the context it is used
func (m *SettleTransactionModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateChangeCode(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCommit(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVerify(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SettleTransactionModel) contextValidateChangeCode(ctx context.Context, formats strfmt.Registry) error {

	if m.ChangeCode != nil {
		if err := m.ChangeCode.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("changeCode")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("changeCode")
			}
			return err
		}
	}

	return nil
}

func (m *SettleTransactionModel) contextValidateCommit(ctx context.Context, formats strfmt.Registry) error {

	if m.Commit != nil {
		if err := m.Commit.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("commit")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("commit")
			}
			return err
		}
	}

	return nil
}

func (m *SettleTransactionModel) contextValidateVerify(ctx context.Context, formats strfmt.Registry) error {

	if m.Verify != nil {
		if err := m.Verify.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("verify")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("verify")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SettleTransactionModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SettleTransactionModel) UnmarshalBinary(b []byte) error {
	var res SettleTransactionModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
