// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TaxSubTypeModel Represents a tax subtype
// Example: {"description":"ALL","id":1,"taxSubType":"*"}
//
// swagger:model TaxSubTypeModel
type TaxSubTypeModel struct {

	// The description of this tax sub-type.
	// Example: ALL
	// Required: true
	Description *string `json:"description"`

	// The unique ID number of this tax sub-type.
	// Example: 1
	// Required: true
	ID *int32 `json:"id"`

	// The unique human readable Id of this tax sub-type.
	// Example: *
	// Required: true
	TaxSubType *string `json:"taxSubType"`

	// The upper level group of tax types.
	// Required: true
	TaxTypeGroup *string `json:"taxTypeGroup"`
}

// Validate validates this tax sub type model
func (m *TaxSubTypeModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTaxSubType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTaxTypeGroup(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TaxSubTypeModel) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

func (m *TaxSubTypeModel) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *TaxSubTypeModel) validateTaxSubType(formats strfmt.Registry) error {

	if err := validate.Required("taxSubType", "body", m.TaxSubType); err != nil {
		return err
	}

	return nil
}

func (m *TaxSubTypeModel) validateTaxTypeGroup(formats strfmt.Registry) error {

	if err := validate.Required("taxTypeGroup", "body", m.TaxTypeGroup); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this tax sub type model based on context it is used
func (m *TaxSubTypeModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TaxSubTypeModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaxSubTypeModel) UnmarshalBinary(b []byte) error {
	var res TaxSubTypeModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
