// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserEntitlementModel User Entitlement Model
// Example: {"accessLevel":"SingleAccount","companies":[123,456,789],"permissions":["CompanyFetch","CompanySave","NexusFetch","NexusSave"]}
//
// swagger:model UserEntitlementModel
type UserEntitlementModel struct {

	// What access privileges does the current user have to see companies?
	// Example: None
	// Enum: [None SingleCompany SingleAccount AllCompanies FirmManagedAccounts]
	AccessLevel string `json:"accessLevel,omitempty"`

	// The identities of all companies this user is permitted to access
	// Example: [123,456,789]
	Companies []int32 `json:"companies"`

	// List of API names and categories that this user is permitted to access
	// Example: ["CompanyFetch","CompanySave","NexusFetch","NexusSave"]
	Permissions []string `json:"permissions"`
}

// Validate validates this user entitlement model
func (m *UserEntitlementModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccessLevel(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var userEntitlementModelTypeAccessLevelPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["None","SingleCompany","SingleAccount","AllCompanies","FirmManagedAccounts"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		userEntitlementModelTypeAccessLevelPropEnum = append(userEntitlementModelTypeAccessLevelPropEnum, v)
	}
}

const (

	// UserEntitlementModelAccessLevelNone captures enum value "None"
	UserEntitlementModelAccessLevelNone string = "None"

	// UserEntitlementModelAccessLevelSingleCompany captures enum value "SingleCompany"
	UserEntitlementModelAccessLevelSingleCompany string = "SingleCompany"

	// UserEntitlementModelAccessLevelSingleAccount captures enum value "SingleAccount"
	UserEntitlementModelAccessLevelSingleAccount string = "SingleAccount"

	// UserEntitlementModelAccessLevelAllCompanies captures enum value "AllCompanies"
	UserEntitlementModelAccessLevelAllCompanies string = "AllCompanies"

	// UserEntitlementModelAccessLevelFirmManagedAccounts captures enum value "FirmManagedAccounts"
	UserEntitlementModelAccessLevelFirmManagedAccounts string = "FirmManagedAccounts"
)

// prop value enum
func (m *UserEntitlementModel) validateAccessLevelEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, userEntitlementModelTypeAccessLevelPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *UserEntitlementModel) validateAccessLevel(formats strfmt.Registry) error {
	if swag.IsZero(m.AccessLevel) { // not required
		return nil
	}

	// value enum
	if err := m.validateAccessLevelEnum("accessLevel", "body", m.AccessLevel); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this user entitlement model based on context it is used
func (m *UserEntitlementModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserEntitlementModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserEntitlementModel) UnmarshalBinary(b []byte) error {
	var res UserEntitlementModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
